/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <net-snmp/agent/cache_handler.h>

#include "data_access/cpqsepci.h"
#include "cpqStdPciSlot.h"
#include "common/smbios.h"

/**---------------------------------------------------------------------*/
/*
 * external per-architecture functions prototypes
 *
 * These shouldn't be called by the general public, so they aren't in
 * the header file.
 */
extern void netsnmp_arch_pcislot_init(void);
extern int netsnmp_arch_pcislot_container_load(netsnmp_container* container);
static void     _cache_free(netsnmp_cache * cache, void *magic);
static int      _cache_load(netsnmp_cache * cache, void *vmagic);


oid cpqSePciSlotTable_oid[] = { 1, 3, 6, 1, 4, 1, 232, 1, 2, 13, 1};
size_t   cpqSePciSlotTable_oid_len = OID_LENGTH(cpqSePciSlotTable_oid);

void
initialize_table_cpqSePciSlotTable(void)
{
    netsnmp_handler_registration *reg;
    netsnmp_mib_handler *handler = NULL;
    netsnmp_container *container = NULL;
    netsnmp_table_registration_info *table_info = NULL;
    netsnmp_cache  *cache = NULL;

    reg =
        netsnmp_create_handler_registration("cpqSePciSlotTable",
                                            cpqSePciSlotTable_handler,
                                            cpqSePciSlotTable_oid,
                                            cpqSePciSlotTable_oid_len,
                                            HANDLER_CAN_RONLY);

    if (NULL == reg) {
        snmp_log(LOG_ERR,"error creating handler registration for "
                 "cpqSePciSlotTable\n");
        goto bail;
    }
    reg->modes |= HANDLER_CAN_NOT_CREATE;

    container = netsnmp_container_find("cpqSePciSlotTable:table_container");
    if (NULL == container) {
        snmp_log(LOG_ERR, "error creating container for cpqSePciSlotTable\n");
        goto bail;
    }

    container->container_name = strdup("PciSlotTable container");

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    if (NULL == table_info) {
        snmp_log(LOG_ERR,"error allocating table registration for "
                 "cpqSePciSlotTable\n");
        goto bail;
    }

    netsnmp_table_helper_add_indexes(table_info,
                                     ASN_INTEGER,
                                     ASN_INTEGER,
                                     0);
    table_info->min_column = CPQSEPCISLOTBUSNUMBERINDEX;
    table_info->max_column = CPQSEPCICURRENTSLOTSPEED;

    /*************************************************
     *
     * inject container_table helper
     */
    handler = netsnmp_container_table_handler_get(table_info, container,
                                            TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    if (NULL == handler) {
        snmp_log(LOG_ERR,"error allocating table registration for "
                 "cpqSePciSlotTable\n");
        goto bail;
    }
    if (SNMPERR_SUCCESS != netsnmp_inject_handler(reg, handler)) {
        snmp_log(LOG_ERR,"error injecting container_table handler for "
                 "cpqSePciSlotTable\n");
        goto bail;
    }
    handler = NULL; /* reg has it, will reuse below */

    /*************************************************
     *
     * inject cache helper
     */
    cache = netsnmp_cache_create(240,    /* timeout in seconds */
                                 _cache_load, _cache_free,
                                 cpqSePciSlotTable_oid,
                                 cpqSePciSlotTable_oid_len); 

    if (NULL == cache) {
        snmp_log(LOG_ERR, "error creating cache for cpqSePciSlotTable\n");
        goto bail;
    }
    cache->flags = NETSNMP_CACHE_DONT_INVALIDATE_ON_SET;
    cache->magic = container;

    handler = netsnmp_cache_handler_get(cache);
    if (NULL == handler) {
        snmp_log(LOG_ERR, "error creating cache handler for cpqSePciSlotTable\n");
        goto bail;
    }

    if (SNMPERR_SUCCESS != netsnmp_inject_handler(reg, handler)) {
        snmp_log(LOG_ERR,"error injecting cache handler for "
                 "cpqSePciSlotTable\n");
        goto bail;
    }
    handler = NULL; /* reg has it*/

    if (SNMPERR_SUCCESS != netsnmp_register_table(reg, table_info)) {
        snmp_log(LOG_ERR,"error registering table handler for "
                 "cpqSePciSlotTable\n");
        goto bail;
    }

    netsnmp_arch_pcislot_init();
    return; /* ok */


  bail: /* not ok */

    if (handler)
        netsnmp_handler_free(handler);

    if (cache)
        netsnmp_cache_free(cache);

    if (table_info)
        netsnmp_table_registration_info_free(table_info);

    if (container)
        CONTAINER_FREE(container);

    if (reg)
        netsnmp_handler_registration_free(reg);

}

/** create a new row in the table */
netsnmp_pcislot_entry *
cpqSePciSlotTable_createEntry(netsnmp_container * container,
                              oid index, oid index2)
{
    netsnmp_pcislot_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(netsnmp_pcislot_entry);
    if (!entry)
        return NULL;

    memset(entry, 0, sizeof(netsnmp_pcislot_entry));
    entry->bus  = index;
    entry->dev  = index2;

    entry->oid_index.len = 2;
    entry->oid_index.oids = (oid *) & entry->bus;
    return entry;
}

#ifdef NOT_NEEDED
/** remove a row from the table */
void
cpqSePciSlotTable_removeEntry(netsnmp_container * container,
                         netsnmp_pcislot_entry * entry)
{

    if (!entry)
        return;                 /* Nothing to remove */
    CONTAINER_REMOVE(container, entry);
    if (entry)
        SNMP_FREE(entry);       /* XXX - release any other internal resources */
}
#endif

/** remove a row from the table */
void
cpqSePciSlotTable_freeEntry(netsnmp_pcislot_entry* entry)
{

    if (!entry)
        return;                 /* Nothing to remove */
    SNMP_FREE(entry);           /* XXX - release any other internal resources */
}

/** handles requests for the hrSWRunTable table */
int
cpqSePciSlotTable_handler(netsnmp_mib_handler *handler,
                     netsnmp_handler_registration *reginfo,
                     netsnmp_agent_request_info *reqinfo,
                     netsnmp_request_info *requests)
{
    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    netsnmp_pcislot_entry *table_entry;

    switch (reqinfo->mode) {
        /*
 *          * Read-support (also covers GetNext requests)
 *                   */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            if (request->processed)
               continue;
            table_entry = (netsnmp_pcislot_entry *)
                netsnmp_container_table_extract_context(request);
            table_info = netsnmp_extract_table_info(request);

            if ((NULL == table_entry) || (NULL == table_info)) {
                snmp_log(LOG_ERR, "could not extract table entry or info for "
                 "cpqSePciSlotTable\n");
                snmp_set_var_typed_value(request->requestvb,
                                         SNMP_ERR_GENERR, NULL, 0);
                continue;
            }
            //DEBUGMSGTL(("pci:arch","entry dump: oid_len=%d, oids=%p &buf[0]t=%p buf=%p bus=%d dev=%d\n" ,
            //                table_entry->oid_index.len, table_entry->oid_index.oids, &table_entry->oid_buf[0],table_entry->oid_buf,table_entry->bus,table_entry->dev));


            DEBUGMSGTL(("pci:arch2","entry dump: bus=%ld, dev=%ld slot=%x subsys_id=%s boardname=%s\n"
                        "slot_width=%d slot_speed=%d ext_info=%x slot_type=%d slot_mode=%d max_Pci_Speed=%d "
                        "max_PciX_Speed=%d current_speed=%d\n",
                        table_entry->bus,table_entry->dev,table_entry->phys_slot,table_entry->subsys_id,table_entry->boardname,
                        table_entry->slot_width,table_entry->slot_speed,table_entry->extended_info,table_entry->slot_type,table_entry->slot_mode,table_entry->max_Pci_Speed,
                        table_entry->max_PciX_Speed,table_entry->current_speed));


            switch (table_info->colnum) {
            case CPQSEPCISLOTBUSNUMBERINDEX:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->bus);
                break;
            case CPQSEPCISLOTDEVICENUMBERINDEX:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->dev);
                break;
            case CPQSEPCIPHYSSLOT:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->phys_slot);
                break;
            case CPQSEPCISLOTSUBSYSTEMID:
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                    (u_char *) table_entry-> subsys_id,
                                    PCISLOT_SUBSYS_SZ);
                break;
            case CPQSEPCISLOTBOARDNAME:
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                    (u_char *) table_entry->boardname,
                                    strlen(table_entry->boardname));
                break;
            case CPQSEPCISLOTWIDTH:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->slot_width);
                break;
            case CPQSEPCISLOTSPEED:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->slot_speed);
                break;
            case CPQSEPCISLOTEXTENDEDINFO:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->extended_info);
                break;
            case CPQSEPCISLOTTYPE:
                if (table_entry->slot_type >= (u_char)sltPCIE)
                    snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           PCI_SLOT_TYPE_PCIE);
                else
                    snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           PCI_SLOT_TYPE_UNKNOWN);
                break;
            case CPQSEPCISLOTCURRENTMODE:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->slot_mode);
                break;
            case CPQSEPCIMAXSLOTSPEED:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->max_Pci_Speed);
                break;
            case CPQSEPCIXMAXSLOTSPEED:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->max_PciX_Speed);
                break;
            case CPQSEPCICURRENTSLOTSPEED:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->current_speed);
                break;
            default:
                /*
                 * An unsupported/unreadable column (if applicable)
                 */
                snmp_set_var_typed_value(request->requestvb,
                                         SNMP_NOSUCHOBJECT, NULL, 0);
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}

/**
 * load pcislot information in specified container
 *
 * @param container empty container to be filled.
 *                  pass NULL to have the function create one.
 *
 * @retval NULL  error
 * @retval !NULL pointer to container
 */
netsnmp_container*
netsnmp_pcislot_container_load(netsnmp_container* user_container)
{
    netsnmp_container* container = user_container;
    int rc;

    DEBUGMSGTL(("pcislot:container:load", "load\n"));

    if (NULL == container) {
        snmp_log(LOG_ERR, "no container specified/found for pcislot\n");
        return NULL;
    }
    
    rc =  netsnmp_arch_pcislot_container_load(container);
    if (0 != rc) {
        if (NULL == user_container) {
            CONTAINER_FREE(container);
            container = NULL;
        }
    }
    
    return container;
}
    

/**
  * @internal
  */
static int
_cache_load(netsnmp_cache * cache, void *vmagic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:cpqSePciSlotTable:_cache_load", "called\n"));

    if ((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache for cpqSePciSlotTable_cache_load\n");
        return -1;
    }
    container = (netsnmp_container *) cache->magic;

    /** should only be called for an invalid or expired cache */
    netsnmp_assert((0 == cache->valid) || (1 == cache->expired));

    netsnmp_pcislot_container_load(container);
    return 0;
}                               /* _cache_load */

/**
 * @Internal
 */
/** remove a row from the table */
static void
cpqSePciSlotTable_freeEntry_cb(netsnmp_pcislot_entry* entry, void *magic)
{

    cpqSePciSlotTable_freeEntry(entry);
}

/**
  * @internal
  */
static void
_cache_free(netsnmp_cache * cache, void *magic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:cpqSePciSlotTable:_cache_free", "called\n"));

    if ((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache in cpqSePciSlotTable_cache_free\n");
        return;
    }
    container = (netsnmp_container *) cache->magic;

    /*
     * empty (but don't free) cache here
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *)
                    cpqSePciSlotTable_freeEntry_cb, NULL);
}                               /* _cache_free */
    
