/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef CPQSEPCIEDISKTABLE_H
#define CPQSEPCIEDISKTABLE_H
extern long     cpqSePCIeDiskTableCondition;

/*
 * function declarations 
 */
extern void            init_cpqSePCIeDisk(void);
extern void            init_cpqSePCIeDiskTable(void);
extern void            initialize_table_cpqSePCIeDiskTable(void);
extern Netsnmp_Node_Handler handle_cpqSePCIeDiskTableCondition;
extern Netsnmp_Node_Handler cpqSePCIeDiskTable_handler;

/** Typical data structure for a row entry */
typedef struct cpqSePCIeDiskTable_entry_s {
    netsnmp_index   oid_index;

    /*
     * Index values 
     */
    long            cpqSePCIeDiskPCIBusIndex;
    long            cpqSePCIeDiskPCIDeviceIndex;
    long            cpqSePCIeDiskPCIFunctionIndex;

    /*
     * Column values 
     */
    char            cpqSePCIeDiskModel[256];
    size_t          cpqSePCIeDiskModel_len;
    char            cpqSePCIeDiskFwRev[256];
    size_t          cpqSePCIeDiskFwRev_len;
    char            cpqSePCIeDiskSerialNumber[256];
    size_t          cpqSePCIeDiskSerialNumber_len;
    u_long          cpqSePCIeDiskCapacityMb;
    long            cpqSePCIeDiskCondition;
    long            cpqSePCIeDiskCurrentTemperature;
    long            cpqSePCIeDiskThresholdTemperature;
    char            cpqSePCIeDiskHwLocation[256];
    size_t          cpqSePCIeDiskHwLocation_len;
    char            cpqSePCIeDiskOsName[256];
    size_t          cpqSePCIeDiskOsName_len;
    long            cpqSePCIeDiskWearStatus;
    u_long          cpqSePCIeDiskPowerOnHours;
    u_long          cpqSePCIeDiskPercntEndrnceUsed;

    long            OldCondition;
    

    int             valid;
} cpqSePCIeDiskTable_entry;

cpqSePCIeDiskTable_entry *
         cpqSePCIeDiskTable_createEntry(netsnmp_container *, oid, oid, oid);
void            init_cpqSePCIeDiskTable(void);
void            initialize_table_cpqSePCIeDiskTable(void);
Netsnmp_Node_Handler cpqSePCIeDiskTable_handler;


#define CPQSEPCIEDISKTABLECONDITION   2
/*
 * column number definitions for table cpqSePCIeDiskTable 
 */
#define COLUMN_CPQSEPCIEDISKPCIBUSINDEX		1
#define COLUMN_CPQSEPCIEDISKPCIDEVICEINDEX		2
#define COLUMN_CPQSEPCIEDISKPCIFUNCTIONINDEX		3
#define COLUMN_CPQSEPCIEDISKMODEL		4
#define COLUMN_CPQSEPCIEDISKFWREV		5
#define COLUMN_CPQSEPCIEDISKSERIALNUMBER		6
#define COLUMN_CPQSEPCIEDISKCAPACITYMB		7
#define COLUMN_CPQSEPCIEDISKCONDITION		8
#define COLUMN_CPQSEPCIEDISKCURRENTTEMPERATURE		9
#define COLUMN_CPQSEPCIEDISKTHRESHOLDTEMPERATURE		10
#define COLUMN_CPQSEPCIEDISKHWLOCATION		11
#define COLUMN_CPQSEPCIEDISKOSNAME		12
#define COLUMN_CPQSEPCIEDISKWEARSTATUS		13
#define COLUMN_CPQSEPCIEDISKPOWERONHOURS		14
#define COLUMN_CPQSEPCIEDISKPERCNTENDRNCEUSED		15

#define NVME_COND_UNKNOWNR  1
#define NVME_COND_OK        2
#define NVME_COND_DEGRADED  3
#define NVME_COND_FAILED    4

#define NVME_WEAR_STATUS_OTHER  1
#define NVME_WEAR_STATUS_OK     2
#define NVME_WEAR_STATUS_FIFTYSIXDAY 3
#define NVME_WEAR_STATUS_FIVEPERCENT 4
#define NVME_WEAR_STATUS_TWOPERCENT 5
#define NVME_WEAR_STATUS_WEAROUT    6
#endif                          /* CPQSEPCIEDISKTABLE_H */
