/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.container.conf 17798 2009-10-27 06:44:54Z magfr $
 */
#ifndef CPQSEPCISLOTTABLE_H
#define CPQSEPCISLOTTABLE_H

#define PCISLOT_BOARDNAME_SZ    256
#define PCISLOT_HW_LOCATION_SZ  256
#define PCISLOT_SUBSYS_SZ       8

#define  PCI_SLOT_SPEED_OTHER       1

#define  PCI_SLOT_TYPE_OTHER        1
#define  PCI_SLOT_TYPE_UNKNOWN      2
#define  PCI_SLOT_TYPE_PCIEXPRESS      6

#define  SMBIOS_PCIE_GEN2       0xab

/** Typical data structure for a row entry */
typedef struct cpqSePciSlotTable_entry_s {
    netsnmp_index   oid_index;

    /*
     * Index values
     */
    oid            cpqSePciSlotBusNumberIndex;
    oid            cpqSePciSlotDeviceNumberIndex;

    /*
     * Column values
     */
    long            cpqSePciPhysSlot;
    char            cpqSePciSlotSubSystemID[PCISLOT_SUBSYS_SZ + 1];
    size_t          cpqSePciSlotSubSystemID_len;
    char            cpqSePciSlotBoardName[PCISLOT_BOARDNAME_SZ];
    size_t          cpqSePciSlotBoardName_len;
    long            cpqSePciSlotWidth;
    long            cpqSePciSlotSpeed;
    long            cpqSePciSlotExtendedInfo;
    long            cpqSePciSlotType;
    long            cpqSePciSlotCurrentMode;
    long            cpqSePciMaxSlotSpeed;
    long            cpqSePciXMaxSlotSpeed;
    long            cpqSePciCurrentSlotSpeed;

    int             valid;
} cpqSePciSlotTable_entry;

/*
 * function declarations 
 */
int netsnmp_arch_pcislot_container_load(netsnmp_container*);
void            init_cpqSePciSlotTable(void);
void            initialize_table_cpqSePciSlotTable(void);
Netsnmp_Node_Handler cpqSePciSlotTable_handler;
cpqSePciSlotTable_entry *
cpqSePciSlotTable_createEntry(netsnmp_container *, oid,  oid);

/*
 * column number definitions for table cpqSePciSlotTable 
 */
#define COLUMN_CPQSEPCISLOTBUSNUMBERINDEX		1
#define COLUMN_CPQSEPCISLOTDEVICENUMBERINDEX		2
#define COLUMN_CPQSEPCIPHYSSLOT		3
#define COLUMN_CPQSEPCISLOTSUBSYSTEMID		4
#define COLUMN_CPQSEPCISLOTBOARDNAME		5
#define COLUMN_CPQSEPCISLOTWIDTH		6
#define COLUMN_CPQSEPCISLOTSPEED		7
#define COLUMN_CPQSEPCISLOTEXTENDEDINFO		8
#define COLUMN_CPQSEPCISLOTTYPE		9
#define COLUMN_CPQSEPCISLOTCURRENTMODE		10
#define COLUMN_CPQSEPCIMAXSLOTSPEED		11
#define COLUMN_CPQSEPCIXMAXSLOTSPEED		12
#define COLUMN_CPQSEPCICURRENTSLOTSPEED		13
#endif                          /* CPQSEPCISLOTTABLE_H */
