/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <net-snmp/agent/cache_handler.h>

#include "data_access/cpqsepci.h"
#include "cpqStdPciMem.h"

/**---------------------------------------------------------------------*/
/*
 * external per-architecture functions prototypes
 *
 * These shouldn't be called by the general public, so they aren't in
 * the header file.
 */
extern void netsnmp_arch_pcimem_init(void);
extern int netsnmp_arch_pcimem_container_load(netsnmp_container* container);
static void     _cache_free(netsnmp_cache * cache, void *magic);
static int      _cache_load(netsnmp_cache * cache, void *vmagic);

/*
 * cpqStdEquipment_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid cpqSePciMemTable_oid[] = { 1, 3, 6, 1, 4, 1, 232, 1, 2, 13, 3};
size_t   cpqSePciMemTable_oid_len = OID_LENGTH(cpqSePciMemTable_oid);

void
    initialize_table_cpqSePciMemTable(void)
{
    netsnmp_handler_registration *reg;
    netsnmp_mib_handler *handler = NULL;
    netsnmp_container *container = NULL;
    netsnmp_table_registration_info *table_info = NULL;
    netsnmp_cache  *cache = NULL;

    reg =
        netsnmp_create_handler_registration("cpqSePciMemTable",
                                            cpqSePciMemTable_handler,
                                            cpqSePciMemTable_oid,
                                            cpqSePciMemTable_oid_len,
                                            HANDLER_CAN_RONLY);

    if (NULL == reg) {
        snmp_log(LOG_ERR,"error creating handler registration for "
                 "cpqSePciMemTable\n");
        goto bail;
    }
    reg->modes |= HANDLER_CAN_NOT_CREATE;
    container = netsnmp_container_find("cpqSePciMemTable:table_container");
    if (NULL == container) {
        snmp_log(LOG_ERR, "error creating container for cpqSePciMemTable\n");
        goto bail;
    }

    container->container_name = strdup("PciMemTable container");

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    if (NULL == table_info) {
        snmp_log(LOG_ERR,"error allocating table registration for "
                 "cpqSePciMemTable\n");
        goto bail;
    }

    netsnmp_table_helper_add_indexes(table_info,
                                     ASN_INTEGER,
                                     ASN_INTEGER,
                                     ASN_INTEGER,
                                     ASN_INTEGER,
                                     0);
    table_info->min_column = CPQSEPCIBUSNUMBERINDEX;
    table_info->max_column = CPQSEPCIMEMSIZE;

    /*************************************************
     *
     * inject container_table helper
     */
    handler = netsnmp_container_table_handler_get(table_info, container,
                                             TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    if (NULL == handler) {
        snmp_log(LOG_ERR,"error allocating table registration for "
                 "cpqSePciMemTable\n");
        goto bail;
    }
    if (SNMPERR_SUCCESS != netsnmp_inject_handler(reg, handler)) {
        snmp_log(LOG_ERR,"error injecting container_table handler for "
                 "cpqSePciMemTable\n");
        goto bail;
    }
    handler = NULL; /* reg has it, will reuse below */

    /*************************************************
     *
     * inject cache helper
     */
    cache = netsnmp_cache_create(240,    /* timeout in seconds */
                                 _cache_load, _cache_free,
                                 cpqSePciMemTable_oid,
                                 cpqSePciMemTable_oid_len);

    if (NULL == cache) {
        snmp_log(LOG_ERR, "error creating cache for cpqSePciMemTable\n");
        goto bail;
    }
    cache->flags = NETSNMP_CACHE_DONT_INVALIDATE_ON_SET;
    cache->magic = container;

    handler = netsnmp_cache_handler_get(cache);
    if (NULL == handler) {
        snmp_log(LOG_ERR, "error creating cache handler for cpqSePciMemTable\n");
        goto bail;
    }

    if (SNMPERR_SUCCESS != netsnmp_inject_handler(reg, handler)) {
        snmp_log(LOG_ERR,"error injecting cache handler for "
                 "cpqSePciMemTable\n");
        goto bail;
    }
    handler = NULL; /* reg has it*/

    if (SNMPERR_SUCCESS != netsnmp_register_table(reg, table_info)) {
        snmp_log(LOG_ERR,"error registering table handler for "
                 "cpqSePciMemTable\n");
        goto bail;
    }

    netsnmp_arch_pcimem_init();
    return; /* ok */


  bail: /* not ok */

    if (handler)
        netsnmp_handler_free(handler);

    if (cache)
        netsnmp_cache_free(cache);

    if (table_info)
        netsnmp_table_registration_info_free(table_info);

    if (container)
        CONTAINER_FREE(container);

    if (reg)
        netsnmp_handler_registration_free(reg);

}

/** create a new row in the table */
netsnmp_pcimem_entry *
cpqSePciMemTable_createEntry(netsnmp_container * container,
                              oid index, oid index2, oid index3, oid index4)
{
    netsnmp_pcimem_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(netsnmp_pcimem_entry);
    if (!entry)
        return NULL;

    memset(entry, 0, sizeof(netsnmp_pcimem_entry));
    entry->bus  = index;
    entry->dev  = index2;
    entry->func = index3;
    entry->mem_index = index4;

    entry->oid_index.len = 4;
    entry->oid_index.oids = (oid *) & entry->bus;
    return entry;
}

#ifdef NOT_NEEDED
/** remove a row from the table */
void
cpqSePciMemTable_removeEntry(netsnmp_container * container,
                         netsnmp_pcimem_entry * entry)
{

    if (!entry)
        return;                 /* Nothing to remove */
    CONTAINER_REMOVE(container, entry);
    if (entry)
        SNMP_FREE(entry);       /* XXX - release any other internal resources */
}
#endif

/** remove a row from the table */
void
cpqSePciMemTable_freeEntry(netsnmp_pcimem_entry* entry)
{

    if (!entry)
        return;                 /* Nothing to remove */
    SNMP_FREE(entry);           /* XXX - release any other internal resources */
}

/** handles requests for the hrSWRunTable table */
int
cpqSePciMemTable_handler(netsnmp_mib_handler *handler,
                     netsnmp_handler_registration *reginfo,
                     netsnmp_agent_request_info *reqinfo,
                     netsnmp_request_info *requests)
{
    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    netsnmp_pcimem_entry *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            if (request->processed)
               continue;
            table_entry = (netsnmp_pcimem_entry *)
                netsnmp_container_table_extract_context(request);
            table_info = netsnmp_extract_table_info(request);
            if ((NULL == table_entry) || (NULL == table_info)) {
                snmp_log(LOG_ERR, "could not extract table entry or info for "
                 "cpqSePciMemTable\n");
                snmp_set_var_typed_value(request->requestvb,
                                         SNMP_ERR_GENERR, NULL, 0);
                continue;
            }

            switch (table_info->colnum) {
            case CPQSEPCIBUSNUMBERINDEX:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->bus);
                break;
            case CPQSEPCIMEMEVICENUMBERINDEX:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->dev);
                break;
            case CPQSEPCIMEMFUNCTIONINDEX:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->func);
                break;
            case CPQSEPCIMEMINDEX:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->mem_index);
                break;
            case CPQSEPCIMEMBASEADDR:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->base_addr);
                break;
            case CPQSEPCIMEMTYPE:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->type);
                break;
            case CPQSEPCIMEMSIZE:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->size);
                break;
            default:
                /*
                 * An unsupported/unreadable column (if applicable)
                 */
                snmp_set_var_typed_value(request->requestvb,
                                         SNMP_NOSUCHOBJECT, NULL, 0);
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}

/**
 * load pcimem information in specified container
 *
 * @param container empty container to be filled.
 *                  pass NULL to have the function create one.
 *
 * @retval NULL  error
 * @retval !NULL pointer to container
 */
netsnmp_container*
netsnmp_pcimem_container_load(netsnmp_container* user_container)
{
    netsnmp_container* container = user_container;
    int rc;

    DEBUGMSGTL(("pcimem:container:load", "load\n"));

    if (NULL == container) {
        snmp_log(LOG_ERR, "no container specified/found for pcimem\n");
        return NULL;
    }

    rc =  netsnmp_arch_pcimem_container_load(container);
    if (0 != rc) {
        if (NULL == user_container) {
             CONTAINER_FREE(container);
            container = NULL;
        }
    }

    return container;
}


/**
 * @internal
 */
static int
_cache_load(netsnmp_cache * cache, void *vmagic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:cpqSePciMemTable:_cache_load", "called\n"));

    if ((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache for cpqSePciMemTable_cache_load\n");
        return -1;
    }
    container = (netsnmp_container *) cache->magic;

    /** should only be called for an invalid or expired cache */
    netsnmp_assert((0 == cache->valid) || (1 == cache->expired));

    netsnmp_pcimem_container_load(container);
    return 0;
}                               /* _cache_load */

/**
 * @Internal
 */
/** remove a row from the table */
static void
cpqSePciMemTable_freeEntry_cb(netsnmp_pcimem_entry* entry, void *magic)
{

    cpqSePciMemTable_freeEntry(entry);
}

/**
 * @internal
 */
static void
_cache_free(netsnmp_cache * cache, void *magic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:cpqSePciMemTable:_cache_free", "called\n"));

    if ((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache in cpqSePciMemTable_cache_free\n");
        return;
    }
    container = (netsnmp_container *) cache->magic;

/*
 * empty (but don't free) cache here
 */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *)
                    cpqSePciMemTable_freeEntry_cb, NULL);
}                               /* _cache_free */

