/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef CPQSEPCIMEM_H
#define CPQSEPCIMEM_H

/*
 * function declarations 
 */

void initialize_table_cpqSePciMemTable();
int cpqSePciMemTable_handler();

#define  MEMORY_TYPE_UNKNOWN    1
#define  MEMORY_TYPE_IO         2
#define  MEMORY_TYPE_MAPPED     3
#define  MEMORY_TYPE_EXPROM     4

#define CPQSEPCIBUSNUMBERINDEX          1
#define CPQSEPCIMEMEVICENUMBERINDEX     2
#define CPQSEPCIMEMFUNCTIONINDEX        3
#define CPQSEPCIMEMINDEX                4
#define CPQSEPCIMEMBASEADDR             5
#define CPQSEPCIMEMTYPE                 6
#define CPQSEPCIMEMSIZE                 7

typedef struct  cpqSePciMemTable_entry{
    netsnmp_index oid_index;
    oid bus;
    oid dev;
    oid func;
    oid mem_index;
    int base_addr;
    int type;
    int size;
} netsnmp_pcimem_entry;


#endif                          /* CPQSEPCIMEM_H */
