/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <net-snmp/agent/table_container.h>
#include "cpqSePCIeDiskTable.h"

const oid       cpqSePCIeDiskTable_oid[] =
        { 1, 3, 6, 1, 4, 1, 232, 1, 2, 23, 1 };
const oid       cpqSePCIeDiskTableCondition_oid[] =
        { 1, 3, 6, 1, 4, 1, 232, 1, 2, 23, 2 };

const size_t    cpqSePCIeDiskTable_oid_len =
        OID_LENGTH(cpqSePCIeDiskTable_oid);

long     cpqSePCIeDiskTableCondition = NVME_COND_OK;

extern int      netsnmp_arch_pciedisk_container_load(netsnmp_container*);
static void     _cache_free(netsnmp_cache * cache, void *magic);
static int      _cache_load(netsnmp_cache * cache, void *vmagic);

int
handle_cpqSePCIeDiskTableCondition(netsnmp_mib_handler *handler,
                                   netsnmp_handler_registration *reginfo,
                                   netsnmp_agent_request_info *reqinfo,
                                   netsnmp_request_info *requests)
{
    long val = 0;

    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        switch (requests->requestvb->name[ reginfo->rootoid_len - 2 ]) {
            case CPQSEPCIEDISKTABLECONDITION:
                val = cpqSePCIeDiskTableCondition;
                break;
            default:
                /*
 *                  * An unsupported/unreadable column (if applicable)
 *                                   */
                snmp_log(LOG_ERR, "unknown object (%lu) in cpqSePCIeDiskTableCondition_handler\n",
                     requests->requestvb->name[ reginfo->rootoid_len - 2 ]);
                netsnmp_set_request_error( reqinfo, requests,
                                            SNMP_NOSUCHOBJECT );
                return SNMP_ERR_NOERROR;
        }
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)&val, sizeof(val));
        break;

    default:
        snmp_log(LOG_ERR, "unknown mode (%d) in cpqSePCIeDiskTableCondition_handler\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}

/** Initializes the cpqSePCIeDiskTable module */
void
init_cpqSePCIeDiskTable(void)
{
    /*
     * here we initialize all the tables we're planning on supporting 
     */
    initialize_table_cpqSePCIeDiskTable();
}

/** Initialize the cpqSePCIeDiskTable table by defining its contents and how it's structured */
void
initialize_table_cpqSePCIeDiskTable(void)
{
    netsnmp_handler_registration *reg = NULL;
    netsnmp_mib_handler *handler = NULL;
    netsnmp_container *container = NULL;
    netsnmp_table_registration_info *table_info = NULL;
    netsnmp_cache  *cache = NULL;

    int reg_tbl_ret = SNMPERR_SUCCESS;

    DEBUGMSGTL(("cpqSePCIeDiskTable:init",
                "initializing table cpqSePCIeDiskTable\n"));

    reg =
        netsnmp_create_handler_registration("cpqSePCIeDiskTable",
                                            cpqSePCIeDiskTable_handler,
                                            cpqSePCIeDiskTable_oid,
                                            cpqSePCIeDiskTable_oid_len,
                                            HANDLER_CAN_RONLY);
    if (NULL == reg) {
        snmp_log(LOG_ERR,
                 "error creating handler registration for cpqSePCIeDiskTable\n");
        goto bail;
    }

    container =
        netsnmp_container_find("cpqSePCIeDiskTable:table_container");
    if (NULL == container) {
        snmp_log(LOG_ERR,
                 "error creating container for cpqSePCIeDiskTable\n");
        goto bail;
    }

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    if (NULL == table_info) {
        snmp_log(LOG_ERR,
                 "error allocating table registration for cpqSePCIeDiskTable\n");
        goto bail;
    }
    netsnmp_table_helper_add_indexes(table_info, 
                                     ASN_INTEGER, /* index: cpqSePCIeDiskPCIBusIndex */
                                     ASN_INTEGER, /* index: cpqSePCIeDiskPCIDeviceIndex */
                                     ASN_INTEGER, /* index: cpqSePCIeDiskPCIFunctIndex */
                                     0);
    table_info->min_column = COLUMN_CPQSEPCIEDISKPCIBUSINDEX;
    table_info->max_column = COLUMN_CPQSEPCIEDISKPERCNTENDRNCEUSED;

    /*************************************************
     *
     * inject container_table helper
     */
    handler = netsnmp_container_table_handler_get(table_info, container,
                                                  TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    if (NULL == handler) {
        snmp_log(LOG_ERR,
                 "error allocating table registration for cpqSePCIeDiskTable\n");
        goto bail;
    }
    if (SNMPERR_SUCCESS != netsnmp_inject_handler(reg, handler)) {
        snmp_log(LOG_ERR,
                 "error injecting container_table handler for cpqSePCIeDiskTable\n");
        goto bail;
    }
    handler = NULL;             /* reg has it, will reuse below */

    /*************************************************
     *
     * inject cache helper
     */
    cache = netsnmp_cache_create(300,    /* timeout in seconds */
                                 _cache_load, _cache_free,
                                 cpqSePCIeDiskTable_oid,
                                 cpqSePCIeDiskTable_oid_len);

    if (NULL == cache) {
        snmp_log(LOG_ERR, "error creating cache for cpqSePCIeDiskTable\n");
        goto bail;
    }
    cache->flags = NETSNMP_CACHE_PRELOAD |
                   NETSNMP_CACHE_DONT_FREE_BEFORE_LOAD |
                   NETSNMP_CACHE_DONT_FREE_EXPIRED |
                   NETSNMP_CACHE_DONT_AUTO_RELEASE |
                   NETSNMP_CACHE_DONT_INVALIDATE_ON_SET;

    cache->magic = container;

    handler = netsnmp_cache_handler_get(cache);
    if (NULL == handler) {
        snmp_log(LOG_ERR,
                 "error creating cache handler for cpqSePCIeDiskTable\n");
        goto bail;
    }

    if (SNMPERR_SUCCESS != netsnmp_inject_handler(reg, handler)) {
        snmp_log(LOG_ERR,
                 "error injecting cache handler for cpqSePCIeDiskTable\n");
        goto bail;
    }
    handler = NULL;             /* reg has it */

    /*
     * register the table
     */
    reg_tbl_ret = netsnmp_register_table(reg, table_info);
    if (reg_tbl_ret != SNMPERR_SUCCESS ) {
        snmp_log(LOG_ERR,
                 "error registering table handler for cpqSePCIeDiskTable\n");
        reg = NULL;             /* it was freed inside netsnmp_register_table */
        goto bail;
    }

    return;                     /* ok */

    /*
     * Some error occurred during registration. Clean up and bail.
     */
  bail:                        /* not ok */

    if (handler)
        netsnmp_handler_free(handler);

    if (cache)
        netsnmp_cache_free(cache);

    if (table_info)
        netsnmp_table_registration_info_free(table_info);

    if (container)
        CONTAINER_FREE(container);

    if (reg_tbl_ret == SNMPERR_SUCCESS)
        if (reg)
            netsnmp_handler_registration_free(reg);
}
/** Initializes the cpqSePCIeDiskTable module */
void
init_cpqSePCIeDisk(void)
{
    /*
     * here we initialize all the tables we're planning on supporting 
     */
    initialize_cpqSePCIeDisk();
}

/** Initializes the cpqSePCIeDisk module */
void
initialize_cpqSePCIeDisk(void)
{
    DEBUGMSGTL(("cpqSePCIeDisk", "Initializing\n"));

    initialize_table_cpqSePCIeDiskTable();

    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("cpqSePCIeDiskTableCondition",
                             handle_cpqSePCIeDiskTableCondition,
                             cpqSePCIeDiskTableCondition_oid,
                             OID_LENGTH(cpqSePCIeDiskTableCondition_oid),
                             HANDLER_CAN_RONLY));
}

/** create a new row in the table */
cpqSePCIeDiskTable_entry *
cpqSePCIeDiskTable_createEntry(netsnmp_container * container,
                               oid  cpqSePCIeDiskPCIBusIndex,
                               oid  cpqSePCIeDiskPCIDeviceIndex,
                               oid  cpqSePCIeDiskPCIFunctionIndex)
{
    cpqSePCIeDiskTable_entry *entry;

    DEBUGMSGTL(("cpqSePCIeDiskTable", "Creating Entry\n"));
    entry = SNMP_MALLOC_TYPEDEF(cpqSePCIeDiskTable_entry);
    if (!entry)
        return NULL;

    entry->cpqSePCIeDiskPCIBusIndex = cpqSePCIeDiskPCIBusIndex;
    entry->cpqSePCIeDiskPCIDeviceIndex = cpqSePCIeDiskPCIDeviceIndex;
    entry->cpqSePCIeDiskPCIFunctionIndex = cpqSePCIeDiskPCIFunctionIndex;
    entry->oid_index.len = 3;
    entry->oid_index.oids = (oid *) &entry->cpqSePCIeDiskPCIBusIndex;

    DEBUGMSGTL(("cpqSePCIeDiskTable", "Created Entry\n"));
    return entry;
}

/** remove a row from the table */
void
cpqSePCIeDiskTable_removeEntry(netsnmp_container * container,
                               cpqSePCIeDiskTable_entry * entry)
{

    if (!entry)
        return;                 /* Nothing to remove */
    CONTAINER_REMOVE(container, entry);
    if (entry)
        SNMP_FREE(entry);       /* XXX - release any other internal resources */
}

/** remove a row from the table */
void
cpqSePCIeDiskTable_freeEntry(cpqSePCIeDiskTable_entry * entry)
{

    if (!entry)
        return;                 /* Nothing to remove */
    SNMP_FREE(entry);           /* XXX - release any other internal resources */
}

/** handles requests for the cpqSePCIeDiskTable table */
int
cpqSePCIeDiskTable_handler(netsnmp_mib_handler *handler,
                           netsnmp_handler_registration *reginfo,
                           netsnmp_agent_request_info *reqinfo,
                           netsnmp_request_info *requests)
{

    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    cpqSePCIeDiskTable_entry *table_entry;

    DEBUGMSGTL(("cpqSePCIeDiskTable:handler", "Processing request (%d)\n",
                reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            if (request->processed)
                continue;
            table_entry = (cpqSePCIeDiskTable_entry *)
                netsnmp_container_table_extract_context(request);
            table_info = netsnmp_extract_table_info(request);
            if ((NULL == table_entry) || (NULL == table_info)) {
                snmp_log(LOG_ERR,
                         "could not extract table entry or info for cpqSePCIeDiskTable\n");
                snmp_set_var_typed_value(request->requestvb,
                                         SNMP_ERR_GENERR, NULL, 0);
                continue;
            }

            switch (table_info->colnum) {
            case COLUMN_CPQSEPCIEDISKPCIBUSINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqSePCIeDiskPCIBusIndex);
                break;
            case COLUMN_CPQSEPCIEDISKPCIDEVICEINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqSePCIeDiskPCIDeviceIndex);
                break;
            case COLUMN_CPQSEPCIEDISKPCIFUNCTIONINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqSePCIeDiskPCIFunctionIndex);
                break;
            case COLUMN_CPQSEPCIEDISKMODEL:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->cpqSePCIeDiskModel,
                                         table_entry->
                                         cpqSePCIeDiskModel_len);
                break;
            case COLUMN_CPQSEPCIEDISKFWREV:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->cpqSePCIeDiskFwRev,
                                         table_entry->
                                         cpqSePCIeDiskFwRev_len);
                break;
            case COLUMN_CPQSEPCIEDISKSERIALNUMBER:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->
                                         cpqSePCIeDiskSerialNumber,
                                         table_entry->
                                         cpqSePCIeDiskSerialNumber_len);
                break;
            case COLUMN_CPQSEPCIEDISKCAPACITYMB:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_GAUGE,
                                           table_entry->
                                           cpqSePCIeDiskCapacityMb);
                break;
            case COLUMN_CPQSEPCIEDISKCONDITION:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqSePCIeDiskCondition);
                break;
            case COLUMN_CPQSEPCIEDISKCURRENTTEMPERATURE:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqSePCIeDiskCurrentTemperature);
                break;
            case COLUMN_CPQSEPCIEDISKTHRESHOLDTEMPERATURE:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqSePCIeDiskThresholdTemperature);
                break;
            case COLUMN_CPQSEPCIEDISKHWLOCATION:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->
                                         cpqSePCIeDiskHwLocation,
                                         table_entry->
                                         cpqSePCIeDiskHwLocation_len);
                break;
            case COLUMN_CPQSEPCIEDISKOSNAME:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->
                                         cpqSePCIeDiskOsName,
                                         table_entry->
                                         cpqSePCIeDiskOsName_len);
                break;
            case COLUMN_CPQSEPCIEDISKWEARSTATUS:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqSePCIeDiskWearStatus);
                break;
            case COLUMN_CPQSEPCIEDISKPOWERONHOURS:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->
                                           cpqSePCIeDiskPowerOnHours);
                break;
            case COLUMN_CPQSEPCIEDISKPERCNTENDRNCEUSED:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_UNSIGNED,
                                           table_entry->
                                           cpqSePCIeDiskPercntEndrnceUsed);
                break;

            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}


/**
 * @internal
 */
static int
_cache_load(netsnmp_cache * cache, void *vmagic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:cpqSePCIeDiskTable:_cache_load", "called\n"));

    if ((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR,
                 "invalid cache for cpqSePCIeDiskTable_cache_load\n");
        return -1;
    }
    container = (netsnmp_container *) cache->magic;

    /** should only be called for an invalid or expired cache */
    netsnmp_assert((0 == cache->valid) || (1 == cache->expired));

    /*
     * load cache here (or call function to do it)
     */
	netsnmp_arch_nvmedrv_container_load(container);

    return 0;
}                               /* _cache_load */

/**
 *  * @Internal
 *   */
/** remove a row from the table */
static void
cpqSePCIeDiskTable_freeEntry_cb(cpqSePCIeDiskTable_entry * entry,
                               void *magic)
{

    cpqSePCIeDiskTable_freeEntry(entry);
}

/**
 * @internal
 */
static void
_cache_free(netsnmp_cache * cache, void *magic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:cpqSePCIeDiskTable:_cache_free", "called\n"));

    if ((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR,
                 "invalid cache in cpqSePCIeDiskTable_cache_free\n");
        return;
    }
    container = (netsnmp_container *) cache->magic;

    /*
     * empty (but don't free) cache here
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *)
                    cpqSePCIeDiskTable_freeEntry_cb, NULL);
}                               /* _cache_free */
