.\" /**************************************************************************
.\"    Copyright 2011 Hewlett-Packard Development Company, L.P.
.\" ***************************************************************************/
.TH AMSHELPER 1m "Nov 1 2015"
.UC 4
.SH NAME
amsHelper - Agentless Management Service daemon.
.SH SYNOPSIS
amsHelper [-f] [-D<string>] -I<interval> -P<interval> -L
.SH DESCRIPTION
The amsHelper enables the iLO4 Agentless Management Service (AMS) to respond to
SNMP queries that it would otherwise not be able to, without amsHelper running.
.SH COMMAND LINE ARGUMENTS
.IP "-f"
Run in the foreground.  
.IP "-D<string>"
Generate Debug messages.  the <string> parameter contains a series of net-snmp debug enable strings delemineted by ','.
.IP "-I<interval>"
The interval parameter indicates how often performance data will be logged to the Active Health System (AHS) log:
.PD 0
.IP
0 = do not log any performance counters (default)
.IP
1 = log performance counters every minute
.IP
2 = log performance counters every 10 minutes
.IP 
3 = log performance counters every hour
.IP "-P<interval>"
The <interval> parameter specifies the number of seconds between RFC 2741 (AgentX) PING requests
.PD 0
.IP
0 = PING Request packets are not sent
.IP
15 = PING Request packets are sent every 15 seconds (default)
.IP "-L"
Do not open a log file; print all messages to stderr.
.IP "-V<string>"
The : separated <string> parameter specifies the leading parts of the RPM Vendor to include in the cpqHoSwVerTable
.PD 1

