/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "cpqFibreArray.h"
//#include "cpqFcahcTable.h"
#include "hpHelper.h"

#define CPQMIB              16
#define CPQMIBREVMAJOR      1
#define CPQMIBREVMINOR      32

oid       cpqFcaMib_oid[] = { 1, 3, 6, 1, 4, 1, 232, 16, 1 };
size_t    cpqFcaMib_oid_len =  OID_LENGTH(cpqFcaMib_oid);

#define CPQFCAMIBREVMAJOR      1
#define CPQFCAMIBREVMINOR      2
#define CPQFCAMIBCONDITION     3

extern void init_cpqFcaHostCntlrTable(void);

/** Initializes the cpqFibreArray module */
void
init_cpqFibreArray(void)
{

    DEBUGMSGTL(("cpqFibreArray", "Initializing\n"));

    cpqHostMibStatusArray[CPQMIB].major = CPQMIBREVMAJOR;
    cpqHostMibStatusArray[CPQMIB].minor = CPQMIBREVMINOR;
    cpqHoMibHealthStatusArray[CPQMIBHEALTHINDEX] = MIB_CONDITION_OK;

    /*
     * register ourselves with the agent to handle our mib tree
     */
    netsnmp_register_scalar_group(
        netsnmp_create_handler_registration("cpqFca", cpqFibreArray_handler,
                             cpqFcaMib_oid, cpqFcaMib_oid_len,
                             HANDLER_CAN_RONLY),
        CPQFCAMIBREVMAJOR, CPQFCAMIBCONDITION);

    init_cpqFcaHostCntlrTable();

    /*
     * place any other initialization junk you need here
     */
    cpqHostMibStatusArray[CPQMIB].stat = MIB_STATUS_AVAILABLE;
    cpqHostMibStatusArray[CPQMIB].cond = MIB_CONDITION_OK;

}

int
cpqFibreArray_handler(netsnmp_mib_handler          *handler,
                      netsnmp_handler_registration *reginfo,
                      netsnmp_agent_request_info   *reqinfo,
                      netsnmp_request_info         *requests)
{
    long val = 0;

    switch (reqinfo->mode) {
    case MODE_GET:
        switch (requests->requestvb->name[ reginfo->rootoid_len - 2 ]) {
            case CPQFCAMIBREVMAJOR:
                val = CPQMIBREVMAJOR;
                break;
            case CPQFCAMIBREVMINOR:
                val = CPQMIBREVMINOR;
                break;
            case CPQFCAMIBCONDITION:
                val = cpqHoMibHealthStatusArray[CPQMIBHEALTHINDEX];
                break;
            default:
                snmp_log(LOG_ERR, "unknown object (%lu) in cpqFibreArray_handler\n",
                     requests->requestvb->name[ reginfo->rootoid_len - 2 ]);
                netsnmp_set_request_error( reqinfo, requests,
                                            SNMP_NOSUCHOBJECT );
                return SNMP_ERR_NOERROR;
        }
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)&val, sizeof(val));
        break;

    default:
        snmp_log(LOG_ERR,
                 "unknown mode (%d) in handle_cpqFcaMibRevMajor\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

