/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#ifndef CPQFIBREARRAY_H
#define CPQFIBREARRAY_H

/*
 * function declarations 
 */
void            init_cpqFibreArray(void);
Netsnmp_Node_Handler cpqFibreArray_handler;

#define CPQMIBHEALTHINDEX       13
#define CPQMIB                  16
#define CPQ_REG_OTHER            1
#define CPQ_REG_OK               2
#define CPQ_REG_DEGRADED         3
#define CPQ_REG_FAILED           4



#endif                          /* CPQFIBREARRAY_H */
