/*
 * Note: this file originally auto-generated by mib2c using
 *  mib2c -c mib2c.container.conf cpqFcaHostCntlrTable
 *  : mib2c.container.conf 17695 2009-07-21 12:22:18Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <net-snmp/agent/table_container.h>

#include "cpqFcaHostCntlrTable.h"
#include "common/nl_udev.h"

#define STATUS_POLL_TIME 600

extern void cpqfca_update_hba_status(char *devpath, char *devname, void *data);
extern int netsnmp_arch_fcahc_container_load(netsnmp_container*);
static void     _cache_free(netsnmp_cache * cache, void *magic);
static int      _cache_load(netsnmp_cache * cache, void *vmagic);

oid       cpqFcaHostCntlrTable_oid[] =
        { 1, 3, 6, 1, 4, 1, 232, 16, 2, 7, 1 };
size_t    cpqFcaHostCntlrTable_oid_len =
        OID_LENGTH(cpqFcaHostCntlrTable_oid);
/** Initializes the cpqFcaHostCntlrTable module */
void
init_cpqFcaHostCntlrTable(void)
{
    /*
     * here we initialize all the tables we're planning on supporting 
     */
    initialize_table_cpqFcaHostCntlrTable();
}

/** Initialize the cpqFcaHostCntlrTable table by defining its contents and how it's structured */
void
initialize_table_cpqFcaHostCntlrTable(void)
{
    netsnmp_handler_registration *reg = NULL;
    netsnmp_mib_handler *handler = NULL;
    netsnmp_container *container = NULL;
    netsnmp_table_registration_info *table_info = NULL;
    netsnmp_cache  *cache = NULL;

    int reg_tbl_ret = SNMPERR_SUCCESS;

    DEBUGMSGTL(("cpqFcaHostCntlrTable:init",
                "initializing table cpqFcaHostCntlrTable\n"));

    reg =
        netsnmp_create_handler_registration("cpqFcaHostCntlrTable",
                                            cpqFcaHostCntlrTable_handler,
                                            cpqFcaHostCntlrTable_oid,
                                            cpqFcaHostCntlrTable_oid_len,
                                            HANDLER_CAN_RONLY);
    if (NULL == reg) {
        snmp_log(LOG_ERR,
                 "error creating handler registration for cpqFcaHostCntlrTable\n");
        goto bail;
    }

    container = netsnmp_container_find("cpqFcaHostCntlrTable:table_container");
    if (NULL == container) {
        snmp_log(LOG_ERR,
                 "error creating container for cpqFcaHostCntlrTable\n");
        goto bail;
    }
    container->container_name = strdup("cpqFcaHostCntlrTable  container");

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    if (NULL == table_info) {
        snmp_log(LOG_ERR,
                 "error allocating table registration for cpqFcaHostCntlrTable\n");
        goto bail;
    }
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER,   /* index: cpqFcaHostCntlrIndex */
                                     0);
    table_info->min_column = COLUMN_CPQFCAHOSTCNTLRINDEX;
    table_info->max_column = COLUMN_CPQFCAHOSTCNTLRPCILOCATION;

    /*************************************************
     *
     * inject container_table helper
     */
    handler = netsnmp_container_table_handler_get(table_info, container,
                                                  TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    if (NULL == handler) {
        snmp_log(LOG_ERR,
                 "error allocating table registration for cpqFcaHostCntlrTable\n");
        goto bail;
    }
    if (SNMPERR_SUCCESS != netsnmp_inject_handler(reg, handler)) {
        snmp_log(LOG_ERR,
                 "error injecting container_table handler for cpqFcaHostCntlrTable\n");
        goto bail;
    }
    handler = NULL;             /* reg has it, will reuse below */

    /*************************************************
     *
     * inject cache helper
     */
    cache = netsnmp_cache_create(STATUS_POLL_TIME,    /* timeout in seconds */
                                 _cache_load, _cache_free,
                                 cpqFcaHostCntlrTable_oid,
                                 cpqFcaHostCntlrTable_oid_len);

    if (NULL == cache) {
        snmp_log(LOG_ERR, "error creating cache for cpqFcaHostCntlrTable\n");
        goto bail;
    }

    cache->flags = NETSNMP_CACHE_PRELOAD |
                   NETSNMP_CACHE_DONT_FREE_BEFORE_LOAD |
                   NETSNMP_CACHE_DONT_FREE_EXPIRED |
                   NETSNMP_CACHE_DONT_AUTO_RELEASE |
                   NETSNMP_CACHE_DONT_INVALIDATE_ON_SET;

    cache->magic = container;

    handler = netsnmp_cache_handler_get(cache);
    if (NULL == handler) {
        snmp_log(LOG_ERR,
                 "error creating cache handler for cpqFcaHostCntlrTable\n");
        goto bail;
    }

    if (SNMPERR_SUCCESS != netsnmp_inject_handler(reg, handler)) {
        snmp_log(LOG_ERR,
                 "error injecting cache handler for cpqFcaHostCntlrTable\n");
        goto bail;
    }
    handler = NULL;             /* reg has it */

    /*
     * register the table
     */
    reg_tbl_ret = netsnmp_register_table(reg, table_info);
    if (reg_tbl_ret != SNMPERR_SUCCESS) {
        snmp_log(LOG_ERR,
                 "error registering table handler for cpqFcaHostCntlrTable\n");
        goto bail;
    }

    udev_register("fc_transport", "add:remove", NULL, cpqfca_update_hba_status, container);

    return;                     /* ok */

    /*
     * Some error occurred during registration. Clean up and bail.
     */
  bail:                        /* not ok */

    if (handler)
        netsnmp_handler_free(handler);

    if (cache)
        netsnmp_cache_free(cache);

    if (table_info)
        netsnmp_table_registration_info_free(table_info);

    if (container)
        CONTAINER_FREE(container);

    if (reg_tbl_ret == SNMPERR_SUCCESS)
        if (reg)
            netsnmp_handler_registration_free(reg);
}

/** create a new row in the table */
cpqFcaHostCntlrTable_entry *
cpqFcaHostCntlrTable_createEntry(netsnmp_container * container,
                                 oid cpqFcaHostCntlrIndex)
{
    cpqFcaHostCntlrTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(cpqFcaHostCntlrTable_entry);
    if (!entry)
        return NULL;

    entry->cpqFcaHostCntlrIndex = cpqFcaHostCntlrIndex;
    entry->oid_index.len = 1;
    entry->oid_index.oids = (oid *) &entry->cpqFcaHostCntlrIndex;
    return entry;
}

/** remove a row from the table */
void
cpqFcaHostCntlrTable_removeEntry(netsnmp_container * container,
                                 cpqFcaHostCntlrTable_entry * entry)
{

    if (!entry)
        return;                 /* Nothing to remove */
    CONTAINER_REMOVE(container, entry);
    if (entry)
        SNMP_FREE(entry);       /* XXX - release any other internal resources */
}

/** remove a row from the table */
void
cpqFcaHostCntlrTable_freeEntry(cpqFcaHostCntlrTable_entry * entry)
{

    if (!entry)
        return;                 /* Nothing to remove */
    SNMP_FREE(entry);           /* XXX - release any other internal resources */
}

/** handles requests for the cpqFcaHostCntlrTable table */
int
cpqFcaHostCntlrTable_handler(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *reqinfo,
                             netsnmp_request_info *requests)
{

    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    cpqFcaHostCntlrTable_entry *table_entry;

    DEBUGMSGTL(("cpqFcaHostCntlrTable:handler",
                "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            if (request->processed)
                continue;
            table_entry = (cpqFcaHostCntlrTable_entry *)
                netsnmp_container_table_extract_context(request);
            table_info = netsnmp_extract_table_info(request);
            if ((NULL == table_entry) || (NULL == table_info)) {
                snmp_log(LOG_ERR,
                         "could not extract table entry or info for cpqFcaHostCntlrTable\n");
                snmp_set_var_typed_value(request->requestvb,
                                         SNMP_ERR_GENERR, NULL, 0);
                continue;
            }

            switch (table_info->colnum) {
            case COLUMN_CPQFCAHOSTCNTLRINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqFcaHostCntlrIndex);
                break;
            case COLUMN_CPQFCAHOSTCNTLRSLOT:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqFcaHostCntlrSlot);
                break;
            case COLUMN_CPQFCAHOSTCNTLRMODEL:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqFcaHostCntlrModel);
                break;
            case COLUMN_CPQFCAHOSTCNTLRSTATUS:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqFcaHostCntlrStatus);
                break;
            case COLUMN_CPQFCAHOSTCNTLRCONDITION:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqFcaHostCntlrCondition);
                break;
            case COLUMN_CPQFCAHOSTCNTLRWORLDWIDENAME:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->
                                         cpqFcaHostCntlrWorldWideName,
                                         table_entry->
                                         cpqFcaHostCntlrWorldWideName_len);
                break;
            case COLUMN_CPQFCAHOSTCNTLRSTORBOXLIST:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->
                                         cpqFcaHostCntlrStorBoxList,
                                         table_entry->
                                         cpqFcaHostCntlrStorBoxList_len);
                break;
            case COLUMN_CPQFCAHOSTCNTLROVERALLCONDITION:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqFcaHostCntlrOverallCondition);
                break;
            case COLUMN_CPQFCAHOSTCNTLRTAPECNTLRLIST:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->
                                         cpqFcaHostCntlrTapeCntlrList,
                                         table_entry->
                                         cpqFcaHostCntlrTapeCntlrList_len);
                break;
            case COLUMN_CPQFCAHOSTCNTLRSERIALNUMBER:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->
                                         cpqFcaHostCntlrSerialNumber,
                                         table_entry->
                                         cpqFcaHostCntlrSerialNumber_len);
                break;
            case COLUMN_CPQFCAHOSTCNTLRHWLOCATION:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->
                                         cpqFcaHostCntlrHwLocation,
                                         table_entry->
                                         cpqFcaHostCntlrHwLocation_len);
                break;
            case COLUMN_CPQFCAHOSTCNTLRWORLDWIDEPORTNAME:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->
                                         cpqFcaHostCntlrWorldWidePortName,
                                         table_entry->
                                         cpqFcaHostCntlrWorldWidePortName_len);
                break;
            case COLUMN_CPQFCAHOSTCNTLRFIRMWAREVERSION:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->
                                         cpqFcaHostCntlrFirmwareVersion,
                                         table_entry->
                                         cpqFcaHostCntlrFirmwareVersion_len);
                break;
            case COLUMN_CPQFCAHOSTCNTLROPTIONROMVERSION:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->
                                         cpqFcaHostCntlrOptionRomVersion,
                                         table_entry->
                                         cpqFcaHostCntlrOptionRomVersion_len);
                break;
            case COLUMN_CPQFCAHOSTCNTLRPCILOCATION:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         (u_char *) table_entry->
                                         cpqFcaHostCntlrPciLocation,
                                         table_entry->
                                         cpqFcaHostCntlrPciLocation_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}

/**
 * @internal
 */
static int
_cache_load(netsnmp_cache * cache, void *vmagic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:cpqFcaHostCntlrTable:_cache_load", "called\n"));

    if ((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR,
                 "invalid cache for cpqFcaHostCntlrTable_cache_load\n");
        return -1;
    }
    container = (netsnmp_container *) cache->magic;

    /** should only be called for an invalid or expired cache */
    netsnmp_assert((0 == cache->valid) || (1 == cache->expired));

    /*
     * load cache here (or call function to do it)
     */
    netsnmp_arch_fcahc_container_load(container);

    return 0;
}                               /* _cache_load */

/**
 * @Internal
 */
/** remove a row from the table */
static void
cpqFcaHostCntlrTable_freeEntry_cb(cpqFcaHostCntlrTable_entry * entry,
                                  void *magic)
{

    cpqFcaHostCntlrTable_freeEntry(entry);
}

/**
 * @internal
 */
static void
_cache_free(netsnmp_cache * cache, void *magic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:cpqFcaHostCntlrTable:_cache_free", "called\n"));

    if ((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache in cpqFcaHostCntlrTable_cache_free\n");
        return;
    }
    container = (netsnmp_container *) cache->magic;

    /*
     * empty (but don't free) cache here
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *)
                    cpqFcaHostCntlrTable_freeEntry_cb, NULL);
}                               /* _cache_free */
