/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef CPQNIC_H
#define CPQNIC_H

#define CPQMIB         18
#define CPQMIBREVMAJOR 1
#define CPQMIBREVMINOR 45
#define CPQMIBHEALTHINDEX 14

#define IFLOGMAPMACADDRESS_LEN 6

/* 
 * we may use header_generic and header_simple_table from the util_funcs module
 */
config_require(util_funcs)

/*
 * function declarations 
 */
Netsnmp_Node_Handler   cpqNic_handler;
void            init_cpqNic(void);
FindVarMethod   var_cpqNic;
FindVarMethod   var_cpqNicIfLogMapTable;
FindVarMethod   var_cpqNicIfPhysAdapterTable;

extern  int InitLibCpqNic(void);
//extern int             NicMibCondition;
extern int             numIfLog;
extern int             numIfPhys;

#endif                          /* CPQNIC_H */
