/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.container.conf 17798 2009-10-27 06:44:54Z magfr $
 */
#ifndef CPQNICIFPHYSADAPTERTABLE_H
#define CPQNICIFPHYSADAPTERTABLE_H

extern const oid       cpqNicIfPhysAdapterTable_oid[];
extern const size_t    cpqNicIfPhysAdapterTable_oid_len;

typedef struct cpqNicIfPhysAdapterTable_entry_s {
    netsnmp_index   oid_index;
    /*
     * Index values 
     */
    oid            cpqNicIfPhysAdapterIndex;

    /*
     * Column values 
     */
    char            cpqNicIfPhysAdapterIfNumber[256];
    size_t          cpqNicIfPhysAdapterIfNumber_len;
    long            cpqNicIfPhysAdapterRole;
    char            cpqNicIfPhysAdapterMACAddress[6];
    size_t          cpqNicIfPhysAdapterMACAddress_len;
    unsigned int    cpqNicIfPhysAdapterSlot;
    long            cpqNicIfPhysAdapterIoAddr;
    long            cpqNicIfPhysAdapterIrq;
    long            cpqNicIfPhysAdapterDma;
    long            cpqNicIfPhysAdapterMemAddr;
    long            cpqNicIfPhysAdapterPort;
    long            cpqNicIfPhysAdapterDuplexState;
    long            cpqNicIfPhysAdapterCondition;
    long            cpqNicIfPhysAdapterState;
    long            cpqNicIfPhysAdapterStatus;
    long            cpqNicIfPhysAdapterPrevCondition;
    long            cpqNicIfPhysAdapterPrevState;
    long            cpqNicIfPhysAdapterPrevStatus;
    long            cpqNicIfPhysAdapterStatsValid;
    u_long          cpqNicIfPhysAdapterGoodTransmits;
    u_long          cpqNicIfPhysAdapterGoodReceives;
    u_long          cpqNicIfPhysAdapterBadTransmits;
    u_long          cpqNicIfPhysAdapterBadReceives;
    u_long          cpqNicIfPhysAdapterAlignmentErrors;
    u_long          cpqNicIfPhysAdapterFCSErrors;
    u_long          cpqNicIfPhysAdapterSingleCollisionFrames;
    u_long          cpqNicIfPhysAdapterMultipleCollisionFrames;
    u_long          cpqNicIfPhysAdapterDeferredTransmissions;
    u_long          cpqNicIfPhysAdapterLateCollisions;
    u_long          cpqNicIfPhysAdapterExcessiveCollisions;
    u_long          cpqNicIfPhysAdapterInternalMacTransmitErrors;
    u_long          cpqNicIfPhysAdapterCarrierSenseErrors;
    u_long          cpqNicIfPhysAdapterFrameTooLongs;
    u_long          cpqNicIfPhysAdapterInternalMacReceiveErrors;
    char            cpqNicIfPhysAdapterHwLocation[256];
    size_t          cpqNicIfPhysAdapterHwLocation_len;
    char            cpqNicIfPhysAdapterPartNumber[256];
    size_t          cpqNicIfPhysAdapterPartNumber_len;
    u_long          cpqNicIfPhysAdapterSpeed;
    long            cpqNicIfPhysAdapterConfSpeedDuplex;
    long            cpqNicIfPhysAdapterAggregationGID;
    u_long          cpqNicIfPhysAdapterSpeedMbps;
    u_long          cpqNicIfPhysAdapterInOctets;
    u_long          cpqNicIfPhysAdapterOutOctets;
    char            cpqNicIfPhysAdapterName[256];
    size_t          cpqNicIfPhysAdapterName_len;
    long            cpqNicIfPhysAdapterIoBayNo;
    char            cpqNicIfPhysAdapterFWVersion[256];
    size_t          cpqNicIfPhysAdapterFWVersion_len;
    long            cpqNicIfPhysAdapterVirtualPortNumber;

    int             AdapterAutoNegotiate;
    oid             cpqHoFwVerIndex;
    int             PCI_Bus;
    int             PCI_Slot;
    int             valid;
} cpqNicIfPhysAdapterTable_entry;

/*
 * function declarations 
 */
cpqNicIfPhysAdapterTable_entry *
     cpqNicIfPhysAdapterTable_createEntry(netsnmp_container *, oid);
void            init_cpqNicIfPhysAdapterTable(void);
void            initialize_table_cpqNicIfPhysAdapterTable(void);
Netsnmp_Node_Handler cpqNicIfPhysAdapterTable_handler;

/*
 * column number definitions for table cpqNicIfPhysAdapterTable 
 */
#define COLUMN_CPQNICIFPHYSADAPTERINDEX		1
#define COLUMN_CPQNICIFPHYSADAPTERIFNUMBER		2
#define COLUMN_CPQNICIFPHYSADAPTERROLE		3
#define COLUMN_CPQNICIFPHYSADAPTERMACADDRESS		4
#define COLUMN_CPQNICIFPHYSADAPTERSLOT		5
#define COLUMN_CPQNICIFPHYSADAPTERIOADDR		6
#define COLUMN_CPQNICIFPHYSADAPTERIRQ		7
#define COLUMN_CPQNICIFPHYSADAPTERDMA		8
#define COLUMN_CPQNICIFPHYSADAPTERMEMADDR		9
#define COLUMN_CPQNICIFPHYSADAPTERPORT		10
#define COLUMN_CPQNICIFPHYSADAPTERDUPLEXSTATE		11
#define COLUMN_CPQNICIFPHYSADAPTERCONDITION		12
#define COLUMN_CPQNICIFPHYSADAPTERSTATE		13
#define COLUMN_CPQNICIFPHYSADAPTERSTATUS		14
#define COLUMN_CPQNICIFPHYSADAPTERSTATSVALID		15
#define COLUMN_CPQNICIFPHYSADAPTERGOODTRANSMITS		16
#define COLUMN_CPQNICIFPHYSADAPTERGOODRECEIVES		17
#define COLUMN_CPQNICIFPHYSADAPTERBADTRANSMITS		18
#define COLUMN_CPQNICIFPHYSADAPTERBADRECEIVES		19
#define COLUMN_CPQNICIFPHYSADAPTERALIGNMENTERRORS		20
#define COLUMN_CPQNICIFPHYSADAPTERFCSERRORS		21
#define COLUMN_CPQNICIFPHYSADAPTERSINGLECOLLISIONFRAMES		22
#define COLUMN_CPQNICIFPHYSADAPTERMULTIPLECOLLISIONFRAMES		23
#define COLUMN_CPQNICIFPHYSADAPTERDEFERREDTRANSMISSIONS		24
#define COLUMN_CPQNICIFPHYSADAPTERLATECOLLISIONS		25
#define COLUMN_CPQNICIFPHYSADAPTEREXCESSIVECOLLISIONS		26
#define COLUMN_CPQNICIFPHYSADAPTERINTERNALMACTRANSMITERRORS		27
#define COLUMN_CPQNICIFPHYSADAPTERCARRIERSENSEERRORS		28
#define COLUMN_CPQNICIFPHYSADAPTERFRAMETOOLONGS		29
#define COLUMN_CPQNICIFPHYSADAPTERINTERNALMACRECEIVEERRORS		30
#define COLUMN_CPQNICIFPHYSADAPTERHWLOCATION		31
#define COLUMN_CPQNICIFPHYSADAPTERPARTNUMBER		32
#define COLUMN_CPQNICIFPHYSADAPTERSPEED		33
#define COLUMN_CPQNICIFPHYSADAPTERCONFSPEEDDUPLEX		34
#define COLUMN_CPQNICIFPHYSADAPTERAGGREGATIONGID		35
#define COLUMN_CPQNICIFPHYSADAPTERSPEEDMBPS		36
#define COLUMN_CPQNICIFPHYSADAPTERINOCTETS		37
#define COLUMN_CPQNICIFPHYSADAPTEROUTOCTETS		38
#define COLUMN_CPQNICIFPHYSADAPTERNAME		39
#define COLUMN_CPQNICIFPHYSADAPTERIOBAYNO		40
#define COLUMN_CPQNICIFPHYSADAPTERFWVERSION		41
#define COLUMN_CPQNICIFPHYSADAPTERVIRTUALPORTNUMBER		42
#endif                          /* CPQNICIFPHYSADAPTERTABLE_H */
