/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef CPQLINOSDISKTABLE_H
#define CPQLINOSDISKTABLE_H

/* Typical data structure for a row entry */
typedef struct cpqLinOsDiskTable_entry_s {
    netsnmp_index   oid_index;

    /*
     * Index values
     */
    oid            cpqLinOsDiskMajorIndex;
    oid            cpqLinOsDiskMinorIndex;

    /*
     * Column values
     */
    char            cpqLinOsDiskName[64];
    size_t          cpqLinOsDiskName_len;
    long            cpqLinOsDiskScsiIndex;
    int            cpqLinOsDiskWriteIos;
    int            cpqLinOsDiskWriteMerges;
    int            cpqLinOsDiskWriteSectors;
    int            cpqLinOsDiskWriteDurationMs;
    int            cpqLinOsDiskWriteIosPerSec;
    int            cpqLinOsDiskWriteSectorsPerSec;
    int            cpqLinOsDiskWriteDurationMsPerIos;
    int            cpqLinOsDiskReadIos;
    int            cpqLinOsDiskReadMerges;
    int            cpqLinOsDiskReadSectors;
    int            cpqLinOsDiskReadDurationMs;
    int            cpqLinOsDiskReadIosPerSec;
    int            cpqLinOsDiskReadSectorsPerSec;
    int            cpqLinOsDiskReadDurationMsPerIos;
    
    unsigned long long            prev_writes;
    unsigned long long            prev_write_merge;
    unsigned long long            prev_write_sectors;
    unsigned long long            prev_write_ms;

    unsigned long long            prev_reads;
    unsigned long long            prev_read_merge;
    unsigned long long            prev_read_sectors;
    unsigned long long            prev_read_ms;

    unsigned long long            curr_writes;
    unsigned long long            curr_write_merge;
    unsigned long long            curr_write_sectors;
    unsigned long long            curr_write_ms;

    unsigned long long            curr_reads;
    unsigned long long            curr_read_merge;
    unsigned long long            curr_read_sectors;
    unsigned long long            curr_read_ms;

    struct timeval prev_time;
    struct timeval curr_time;

    time_t	    last_tick;

    int             valid;
} cpqLinOsDiskTable_entry;

/*
 * function declarations 
 */
cpqLinOsDiskTable_entry *
cpqLinOsDiskTable_createEntry(netsnmp_container * container,
                              oid cpqLinOsDiskMajorIndex,
                              oid cpqLinOsDiskMinorIndex);

void            init_cpqLinOsDiskTable(void);
void            initialize_table_cpqLinOsDiskTable(void);
Netsnmp_Node_Handler cpqLinOsDiskTable_handler;

/*
 * column number definitions for table cpqLinOsDiskTable 
 */
#define COLUMN_CPQLINOSDISKMAJORINDEX		     1
#define COLUMN_CPQLINOSDISKMINORINDEX		     2
#define COLUMN_CPQLINOSDISKNAME		             3
#define COLUMN_CPQLINOSDISKSCSIINDEX		     4
#define COLUMN_CPQLINOSDISKWRITEIOS		     5
#define COLUMN_CPQLINOSDISKWRITEMERGES		     6
#define COLUMN_CPQLINOSDISKWRITESECTORS		     7
#define COLUMN_CPQLINOSDISKWRITEDURATIONMS	     8
#define COLUMN_CPQLINOSDISKWRITEIOSPERSEC	     9
#define COLUMN_CPQLINOSDISKWRITESECTORSPERSEC	    10
#define COLUMN_CPQLINOSDISKWRITEDURATIONMSPERIOS    11
#define COLUMN_CPQLINOSDISKREADIOS		    12
#define COLUMN_CPQLINOSDISKREADMERGES		    13
#define COLUMN_CPQLINOSDISKREADSECTORS		    14
#define COLUMN_CPQLINOSDISKREADDURATIONMS	    15
#define COLUMN_CPQLINOSDISKREADIOSPERSEC	    16
#define COLUMN_CPQLINOSDISKREADSECTORSPERSEC	    17
#define COLUMN_CPQLINOSDISKREADDURATIONMSPERIOS	    18
#endif                          /* CPQLINOSDISKTABLE_H */
