/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef CPQLINOSNETWORKINTERFACETABLE_H
#define CPQLINOSNETWORKINTERFACETABLE_H

/* Typical data structure for a row entry */
typedef struct cpqLinOsNetworkInterfaceTable_entry_s {
    netsnmp_index   oid_index;

    /*
     * Index values
     */
    oid            cpqLinOsNetworkInterfaceIndex;
    /*
     * Column values
     */
    char                 cpqLinOsNetworkInterfaceName[64];
    size_t               cpqLinOsNetworkInterfaceName_len;
    unsigned long long   cpqLinOsNetworkInterfaceTxBytes;
    unsigned long long   cpqLinOsNetworkInterfaceTxPackets;
    long                 cpqLinOsNetworkInterfaceTxBytesPerSec;
    long                 cpqLinOsNetworkInterfaceTxPacketsPerSec;
    unsigned long long   cpqLinOsNetworkInterfaceRxBytes;
    unsigned long long   cpqLinOsNetworkInterfaceRxPackets;
    long                 cpqLinOsNetworkInterfaceRxBytesPerSec;
    long                 cpqLinOsNetworkInterfaceRxPacketsPerSec;

    unsigned long long   prev_txbytes;
    unsigned long long   prev_txpkts;
    unsigned long long   prev_rxbytes;
    unsigned long long   prev_rxpkts;
    unsigned long long   curr_txbytes;
    unsigned long long   curr_txpkts;
    unsigned long long   curr_rxbytes;
    unsigned long long   curr_rxpkts;

    time_t	    last_tic;

    struct timeval prev_time;
    struct timeval curr_time;

    int             valid;
} cpqLinOsNetworkInterfaceTable_entry;


/*
 * function declarations 
 */
cpqLinOsNetworkInterfaceTable_entry *
cpqLinOsNetworkInterfaceTable_createEntry(netsnmp_container * container,
                                          oid
                                          cpqLinOsNetworkInterfaceIndex);
void            init_cpqLinOsNetworkInterfaceTable(void);
void            initialize_table_cpqLinOsNetworkInterfaceTable(void);
Netsnmp_Node_Handler cpqLinOsNetworkInterfaceTable_handler;

/*
 * column number definitions for table cpqLinOsNetworkInterfaceTable 
 */
#define COLUMN_CPQLINOSNETWORKINTERFACEINDEX		         1
#define COLUMN_CPQLINOSNETWORKINTERFACENAME		             2
#define COLUMN_CPQLINOSNETWORKINTERFACETXBYTES		         3
#define COLUMN_CPQLINOSNETWORKINTERFACETXPACKETS		     4
#define COLUMN_CPQLINOSNETWORKINTERFACETXBYTESPERSEC		 5
#define COLUMN_CPQLINOSNETWORKINTERFACETXPACKETSPERSEC		 6
#define COLUMN_CPQLINOSNETWORKINTERFACERXBYTES		         7
#define COLUMN_CPQLINOSNETWORKINTERFACERXPACKETS		     8
#define COLUMN_CPQLINOSNETWORKINTERFACERXBYTESPERSEC		 9
#define COLUMN_CPQLINOSNETWORKINTERFACERXPACKETSPERSEC		10
#endif                          /* CPQLINOSNETWORKINTERFACETABLE_H */
