#define MYTABLE "cpqHoFileSysTable"
#define CPQHO_FILESYS_INDEX             1
#define CPQHO_FILESYS_DESC              2
#define CPQHO_FILESYS_SPACETOTAL        3
#define CPQHO_FILESYS_SPACEUSED         4
#define CPQHO_FILESYS_PERCENTSPACEUSED  5
#define CPQHO_FILESYS_ALLOCUNITSTOTAL   6
#define CPQHO_FILESYS_ALLOCUNITSUSED    7
#define CPQHO_FILESYS_STATUS            8

#define MIB_STATE_OK          2


