/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef CPQHOSWRUNNINGTABLE_H
#define CPQHOSWRUNNINGTABLE_H

typedef struct cpqHoSWRunningTable_entry_s {
    netsnmp_index   oid_index;

    /*
     * Index values
     */
    oid            cpqHoSWRunningIndex;

    /*
     * Column values
     */
    char            cpqHoSWRunningName[256];
    size_t          cpqHoSWRunningName_len;
    char            cpqHoSWRunningDesc[256];
    size_t          cpqHoSWRunningDesc_len;
    char            cpqHoSWRunningVersion[256];
    size_t          cpqHoSWRunningVersion_len;
    char            cpqHoSWRunningDate[8];
    size_t          cpqHoSWRunningDate_len;
    long            cpqHoSWRunningMonitor;
    long            cpqHoSWRunningState;
    long            cpqHoSWRunningCount;
    long            cpqHoSWRunningCountMin;
    long            cpqHoSWRunningCountMax;
    char            cpqHoSWRunningEventTime[8];
    size_t          cpqHoSWRunningEventTime_len;
    long            cpqHoSWRunningStatus;
    long            cpqHoSWRunningConfigStatus;
    char            cpqHoSWRunningIdentifier[256];
    size_t          cpqHoSWRunningIdentifier_len;
    long            cpqHoSWRunningRedundancyMode;

    int             valid;
} cpqHoSWRunningTable_entry;

/*
 * function declarations 
 */
cpqHoSWRunningTable_entry *
    cpqHoSWRunningTable_createEntry(netsnmp_container *, oid);

void            init_cpqHoSWRunningTable(void);
void            initialize_table_cpqHoSWRunningTable(void);
Netsnmp_Node_Handler cpqHoSWRunningTable_handler;

#define CPQHOSWRUNNINGTABLE_TIMEOUT  60

/*
 * column number definitions for table cpqHoSWRunningTable 
 */
#define COLUMN_CPQHOSWRUNNINGINDEX		1
#define COLUMN_CPQHOSWRUNNINGNAME		2
#define COLUMN_CPQHOSWRUNNINGDESC		3
#define COLUMN_CPQHOSWRUNNINGVERSION		4
#define COLUMN_CPQHOSWRUNNINGDATE		5
#define COLUMN_CPQHOSWRUNNINGMONITOR		6
#define COLUMN_CPQHOSWRUNNINGSTATE		7
#define COLUMN_CPQHOSWRUNNINGCOUNT		8
#define COLUMN_CPQHOSWRUNNINGCOUNTMIN		9
#define COLUMN_CPQHOSWRUNNINGCOUNTMAX		10
#define COLUMN_CPQHOSWRUNNINGEVENTTIME		11
#define COLUMN_CPQHOSWRUNNINGSTATUS		12
#define COLUMN_CPQHOSWRUNNINGCONFIGSTATUS		13
#define COLUMN_CPQHOSWRUNNINGIDENTIFIER		14
#define COLUMN_CPQHOSWRUNNINGREDUNDANCYMODE		15

#endif                          /* CPQHOSWRUNNINGTABLE_H */

