/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <net-snmp/agent/table_container.h>
#include <net-snmp/agent/agent_index.h>
#include "cpqHoFwVerTable.h"

extern void *netsnmp_table_row_extract(netsnmp_request_info *);
oid       cpqHoFwVerTable_oid[] = 
              { 1, 3, 6, 1, 4, 1, 232, 11, 2, 14, 1 };
const size_t    cpqHoFwVerTable_oid_len = OID_LENGTH(cpqHoFwVerTable_oid);
int   other_fw_idx = 50;
int   nic_fw_idx = 255;
netsnmp_variable_list *
cpqHoFwVerTable_buildIndexList(cpqHoFwVerTable_entry *);

/** Initializes the cpqHoFwVerTable module */
void
init_cpqHoFwVerTable(void)
{
    /*
     * here we initialize all the tables we're planning on supporting 
     */
    initialize_table_cpqHoFwVerTable();
}

/** Initialize the cpqHoFwVerTable table by defining its contents and how it's structured */
void
initialize_table_cpqHoFwVerTable(void)
{

    DEBUGMSGTL(("cpqHoFwVerTable:init",
                "initializing table cpqHoFwVerTable\n"));

}

/** create a new row in the table */
cpqHoFwVerTable_entry *
cpqHoFwVerTable_createEntry(oid cpqHoFwVerIndex)
{
    cpqHoFwVerTable_entry *entry;
    netsnmp_handler_registration *reg = NULL;
    netsnmp_table_registration_info *table_info = NULL;
    netsnmp_variable_list *idxs;

    reg =
        netsnmp_create_handler_registration("cpqHoFwVerTable",
                                            cpqHoFwVerTable_handler,
                                            cpqHoFwVerTable_oid,
                                            cpqHoFwVerTable_oid_len,
                                            HANDLER_CAN_RONLY);

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);

    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER,   /* index: cpqHoFwVerIndex */
                                     0);
    table_info->min_column = COLUMN_CPQHOFWVERINDEX;
    table_info->max_column = COLUMN_CPQHOFWVERUPDATEMETHOD;

    DEBUGMSGTL(("cpqHoFwVerTable:init",
                "FW_table_info = %p, reg = %p\n", table_info, reg));

    entry = SNMP_MALLOC_TYPEDEF(cpqHoFwVerTable_entry);
    if (!entry)
        return NULL;

    entry->cpqHoFwVerIndex = cpqHoFwVerIndex;
    entry->oid_index.len = 1;
    entry->oid_index.oids = (oid *) &entry->cpqHoFwVerIndex;

    idxs = cpqHoFwVerTable_buildIndexList(entry);
    netsnmp_table_row_register(reg, table_info, entry, idxs);

    return entry;
}

netsnmp_variable_list *
cpqHoFwVerTable_buildIndexList(cpqHoFwVerTable_entry * row)
{
    netsnmp_variable_list *v1 = NULL, *v2;

    if (!row)
        return NULL;

    v1 = SNMP_MALLOC_TYPEDEF(netsnmp_variable_list);
    v2 = v1;
    snmp_set_var_typed_integer(v2, ASN_INTEGER, row->cpqHoFwVerIndex);

    return v1;
}

/** handles requests for the cpqHoFwVerTable table */
int
cpqHoFwVerTable_handler(netsnmp_mib_handler *handler,
                        netsnmp_handler_registration *reginfo,
                        netsnmp_agent_request_info *reqinfo,
                        netsnmp_request_info *requests)
{

    netsnmp_request_info *request;
    cpqHoFwVerTable_entry *table_entry;

    DEBUGMSGTL(("cpqHoFwVerTable:handler", "Processing request (%d)\n",
                reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            table_entry = (cpqHoFwVerTable_entry *)
                netsnmp_table_row_extract(request);

            switch (request->requestvb->name[11 + 1]) {
            case COLUMN_CPQHOFWVERINDEX:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->cpqHoFwVerIndex);
                break;
            case COLUMN_CPQHOFWVERCATEGORY:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqHoFwVerCategory);
                break;
            case COLUMN_CPQHOFWVERDEVICETYPE:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqHoFwVerDeviceType);
                break;
            case COLUMN_CPQHOFWVERDISPLAYNAME:
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->
                                         cpqHoFwVerDisplayName,
                                         table_entry->
                                         cpqHoFwVerDisplayName_len);
                break;
            case COLUMN_CPQHOFWVERVERSION:
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->cpqHoFwVerVersion,
                                         table_entry->
                                         cpqHoFwVerVersion_len);
                break;
            case COLUMN_CPQHOFWVERLOCATION:
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->cpqHoFwVerLocation,
                                         table_entry->
                                         cpqHoFwVerLocation_len);
                break;
            case COLUMN_CPQHOFWVERXMLSTRING:
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->cpqHoFwVerXmlString,
                                         table_entry->
                                         cpqHoFwVerXmlString_len);
                break;
            case COLUMN_CPQHOFWVERKEYSTRING:
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->cpqHoFwVerKeyString,
                                         table_entry->
                                         cpqHoFwVerKeyString_len);
                break;
            case COLUMN_CPQHOFWVERUPDATEMETHOD:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->
                                           cpqHoFwVerUpdateMethod);
                break;
            default:
                /*
 *                  * An unsupported/unreadable column (if applicable)
 *                                   */
                snmp_set_var_typed_value(request->requestvb,
                                         SNMP_NOSUCHOBJECT, NULL, 0);
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}

int unregister_FW_version(int fw_idx)
{
    int idx = 0;
    idx = unregister_int_index(cpqHoFwVerTable_oid,
            cpqHoFwVerTable_oid_len,
            fw_idx);
    DEBUGMSGTL(("cpqHoFwVerTable:init",
                "cpqHoFwVerTable unregister idx %d = %d\n",
                fw_idx, idx));
    return idx;
}

int register_FW_version(int dir, int fw_idx, int cat, int type,  int update, 
                        char *fw_version, char *name, char *location, char *key)
{
    int idx = 0;
    cpqHoFwVerTable_entry *fw_entry;

    idx = unregister_int_index(cpqHoFwVerTable_oid,
            cpqHoFwVerTable_oid_len,
            fw_idx);
    DEBUGMSGTL(("cpqHoFwVerTable:init",
                "cpqHoFwVerTable unregister idx %d = %d\n",
                fw_idx, idx));
    idx = register_int_index(cpqHoFwVerTable_oid,
            cpqHoFwVerTable_oid_len,
            fw_idx);

    DEBUGMSGTL(("cpqHoFwVerTable:init",
                "cpqHoFwVerTable register idx %d = %d\n",
                fw_idx, idx));
    if (idx != -1) {
        fw_idx = idx + dir;
        DEBUGMSGTL(("cpqHoFwVerTable:init",
                    "cpqHoFwVerTable next fw_idx = %d\n",
                    fw_idx));

        fw_entry = cpqHoFwVerTable_createEntry((oid)idx);
        if (fw_entry) {
            DEBUGMSGTL(("cpqHoFwVerTable:init",
                        "cpqHoFwVerTable entry = %p\n",
                        fw_entry));

            fw_entry->cpqHoFwVerIndex = idx;

            fw_entry->cpqHoFwVerCategory = cat;
            fw_entry->cpqHoFwVerDeviceType = type;
            fw_entry->cpqHoFwVerUpdateMethod = update;

            strcpy(fw_entry->cpqHoFwVerVersion, fw_version);
            fw_entry->cpqHoFwVerVersion_len = strlen(fw_version);

            strcpy(fw_entry->cpqHoFwVerDisplayName, name);
            fw_entry->cpqHoFwVerDisplayName_len = strlen(name);

            strcpy(fw_entry->cpqHoFwVerLocation, location);
            fw_entry->cpqHoFwVerLocation_len = strlen(location);

            strcpy(fw_entry->cpqHoFwVerKeyString, key);
            fw_entry->cpqHoFwVerKeyString_len = strlen(key);
        }
    }
    return fw_idx;
}

