/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef CPQHOSWVERTABLE_H
#define CPQHOSWVERTABLE_H

oid cpqHoSwVerNextIndex;

typedef struct cpqHoSwVerTable_entry_s {
    netsnmp_index   oid_index;

    /*
     * Index values
     */
    oid            cpqHoSwVerIndex;

    /*
     * Column values
     */
    long            cpqHoSwVerStatus;
    long            cpqHoSwVerType;
    char            cpqHoSwVerName[128];
    size_t          cpqHoSwVerName_len;
    char            cpqHoSwVerDescription[128];
    size_t          cpqHoSwVerDescription_len;
    unsigned char   cpqHoSwVerDate[8];
    size_t          cpqHoSwVerDate_len;
    char            cpqHoSwVerLocation[128];
    size_t          cpqHoSwVerLocation_len;
    char            cpqHoSwVerVersion[50];
    size_t          cpqHoSwVerVersion_len;
    char            cpqHoSwVerVersionBinary[50];
    size_t          cpqHoSwVerVersionBinary_len;

    time_t	    timestamp;
    char 	    vendor[80];
    int 	    vendor_len;
    int             valid;
} cpqHoSwVerTable_entry;

/*
 * function declarations 
 */
cpqHoSwVerTable_entry *
    cpqHoSwVerTable_createEntry(netsnmp_container *, oid);

void            init_cpqHoSwVerTable(void);
void            initialize_table_cpqHoSwVerTable(void);
Netsnmp_Node_Handler cpqHoSwVerTable_handler;

#define CPQHOSWVERTABLE_TIMEOUT  60

/*
 * column number definitions for table cpqHoSwVerTable 
 */
#define COLUMN_CPQHOSWVERINDEX		1
#define COLUMN_CPQHOSWVERSTATUS		2
#define COLUMN_CPQHOSWVERTYPE		3
#define COLUMN_CPQHOSWVERNAME		4
#define COLUMN_CPQHOSWVERDESCRIPTION	5
#define COLUMN_CPQHOSWVERDATE		6
#define COLUMN_CPQHOSWVERLOCATION	7
#define COLUMN_CPQHOSWVERVERSION	8
#define COLUMN_CPQHOSWVERVERSIONBINARY	9

#endif                          /* CPQHOSWVERTABLE_H */

