/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef CPQIDE_H
#define CPQIDE_H

#define CPQMIB                  14
#define CPQMIBREVMAJOR          1
#define CPQMIBREVMINOR          9
#define CPQMIBHEALTHINDEX       12

#define CPQIDEMIBREVMAJOR               1
#define CPQIDEMIBREVMINOR               2
#define CPQIDEMIBCONDITION              3

#define CPQ_REG_OTHER            1
#define CPQ_REG_OK               2
#define CPQ_REG_DEGRADED         3
#define CPQ_REG_FAILED           4

/*
 * function declarations 
 */
Netsnmp_Node_Handler   cpqIde_handler;
void              init_cpqIde(void);

#endif                          /* CPQIDE_H */
