/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <net-snmp/agent/cache_handler.h>

#include "cpqIdeCntlr.h"
#include "data_access/idecntlr.h"

int CntlrCondition;

void initialize_table_cpqIdeCntlrTable();
int cpqIdeCntlrTable_handler();

/*
 * cpqIdeCntlrTable_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid cpqIdeCntlrTable_oid[] = { 1, 3, 6, 1, 4, 1, 232, 14, 2, 3, 1};
size_t   cpqIdeCntlrTable_oid_len = OID_LENGTH(cpqIdeCntlrTable_oid);

void
    initialize_table_cpqIdeCntlrTable(void)
{
    DEBUGMSGTL(("cpqIde", "Initializing IDE Controller Table\n"));

    netsnmp_handler_registration *reg;
    netsnmp_mib_handler *handler = NULL;
    netsnmp_table_registration_info *table_info = NULL;

    reg =
        netsnmp_create_handler_registration("cpqIdeCntlrTable",
                                            cpqIdeCntlrTable_handler,
                                            cpqIdeCntlrTable_oid,
                                            cpqIdeCntlrTable_oid_len,
                                            HANDLER_CAN_RONLY);

    if (NULL == reg) {
        snmp_log(LOG_ERR,"error creating handler registration for "
                 "cpqIdeCntlrTable\n");
        goto bail;
    }
    reg->modes |= HANDLER_CAN_NOT_CREATE;

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    if (NULL == table_info) {
        snmp_log(LOG_ERR,"error allocating table registration for "
                 "cpqIdeCntlrTable\n");
        goto bail;
    }

    netsnmp_table_helper_add_indexes(table_info, 
                                     ASN_INTEGER,
                                     0);
    table_info->min_column = CPQIDECNTLRINDEX;
    table_info->max_column = CPQIDECNTLRSERIALNUMBER;

    /*************************************************
     *
     * inject container_table helper
     */
    handler = netsnmp_container_table_handler_get(table_info, 
                                                netsnmp_idecntlr_container(),
                                           TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    if (NULL == handler) {
        snmp_log(LOG_ERR,"error allocating table registration for "
                 "cpqIdeCntlrTable\n");
        goto bail;
    }
    if (SNMPERR_SUCCESS != netsnmp_inject_handler(reg, handler)) {
        snmp_log(LOG_ERR,"error injecting container_table handler for "
                 "cpqIdeCntlrTable\n");
        goto bail;
    }
    handler = NULL; /* reg has it, will reuse below */

    /*************************************************
     *
     * inject cache helper
     */
    handler = netsnmp_cache_handler_get(netsnmp_idecntlr_cache());
    if (NULL == handler) {
        snmp_log(LOG_ERR, "error creating cache handler for cpqIdeCntlrTable\n");
        goto bail;
    }

    if (SNMPERR_SUCCESS != netsnmp_inject_handler(reg, handler)) {
        snmp_log(LOG_ERR,"error injecting cache handler for "
                 "cpqIdeCntlrTable\n");
        goto bail;
    }
    handler = NULL; /* reg has it*/

    if (SNMPERR_SUCCESS != netsnmp_register_table(reg, table_info)) {
        snmp_log(LOG_ERR,"error registering table handler for "
                 "cpqIdeCntlrTable\n");
        goto bail;
    }

    //init_idecntlr();
    return; /* ok */


  bail: /* not ok */

    if (handler)
        netsnmp_handler_free(handler);

    if (table_info)
        netsnmp_table_registration_info_free(table_info);

    if (reg)
        netsnmp_handler_registration_free(reg);

}


int
cpqIdeCntlrTable_handler(netsnmp_mib_handler *handler,
                     netsnmp_handler_registration *reginfo,
                     netsnmp_agent_request_info *reqinfo,
                     netsnmp_request_info *requests)
{
    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    netsnmp_idecntlr_entry *table_entry;

    DEBUGMSGTL(("cpqIde", "IDE Controller Table Entry\n"));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            if (request->processed)
               continue;
            table_entry = (netsnmp_idecntlr_entry *)
                netsnmp_container_table_extract_context(request);
            table_info = netsnmp_extract_table_info(request);
            if ((NULL == table_entry) || (NULL == table_info)) {
                snmp_log(LOG_ERR, "could not extract table entry or info for "
                 "cpqIdeCntlrTable\n");
                snmp_set_var_typed_value(request->requestvb,
                                         SNMP_ERR_GENERR, NULL, 0);
                continue;
            }

            switch (table_info->colnum) {
            case CPQIDECNTLRINDEX:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->Index);
                break;
            case CPQIDECNTLROVERALLCONDITION:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->OverallCondition);
                break;
            case CPQIDECNTLRMODEL:
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                   (u_char *) table_entry->Model,
                                    strlen(table_entry->Model));
                break;
            case CPQIDECNTLRFWREV:
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                   (u_char *) table_entry->FwRev,
                                    strlen(table_entry->FwRev));
                break;
            case CPQIDECNTLRSLOT:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->Slot);
                break;
            case CPQIDECNTLRSTATUS:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->Status);
                break;
            case CPQIDECNTLRCONDITION:
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->Condition);
                break;
            case CPQIDECNTLRSERIALNUMBER:
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                   (u_char *) table_entry->SerialNumber,
                                    strlen(table_entry->SerialNumber));
                break;
            default:
                /*
                 * An unsupported/unreadable column (if applicable)
                 */
                snmp_set_var_typed_value(request->requestvb,
                                         SNMP_NOSUCHOBJECT, NULL, 0);
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}



