/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef CPQIDECNTLR_H
#define CPQIDECNTLR_H

/*
 * function declarations 
 */
void initialize_table_cpqIdeCntlrTable();
int cpqIdeCntlrTable_handler();
extern int CntlrCondition;

/*
 * cpqIdeCntlrTable_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

extern oid cpqIdeCntlrTable_oid[];
extern size_t   cpqIdeCntlrTable_oid_len;

#define CPQIDECNTLRINDEX                1
#define CPQIDECNTLROVERALLCONDITION     2
#define CPQIDECNTLRMODEL                3
#define CPQIDECNTLRFWREV                4
#define CPQIDECNTLRSLOT                 5
#define CPQIDECNTLRSTATUS               6
#define CPQIDECNTLRCONDITION            7
#define CPQIDECNTLRSERIALNUMBER         8

typedef struct  cpqIdeCntlrTable_entry{
    netsnmp_index  oid_index;
    int            Index;  
    int            OverallCondition;
    char           Model[80];    
    char           FwRev[17];
    int            Slot;
    int            Status; 
    int            Condition;
    char           SerialNumber[81];
    char           Host[20];
} netsnmp_idecntlr_entry;

#endif                          /* CPQIDECNTLR_H */
