/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef CPQIDEDISK_H
#define CPQIDEDISK_H

/*
 * function declarations 
 */
void initialize_table_cpqIdeDiskTable();
int cpqIdeDiskTable_handler();

/*
 * cpqIdeDisk_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

extern int DriveCondition;
extern oid cpqIdeDiskTable_oid[];
extern size_t   cpqIdeDiskTable_oid_len;

#define CPQIDEDISKCONTROLLERINDEX             1
#define CPQIDEDISKINDEX                       2
#define CPQIDEDISKMODEL                       3
#define CPQIDEDISKFWREV                       4
#define CPQIDEDISKSERIALNUMBER                5
#define CPQIDEDISKSTATUS                      6
#define CPQIDEDISKCONDITION                   7
#define CPQIDEDISKCAPACITY                    8
#define CPQIDEDISKSMARTENABLED                9
#define CPQIDEDISKTRANSFERMODE               10
#define CPQIDEDISKCHANNEL                    11
#define CPQIDEDISKNUMBER                     12
#define CPQIDEDISKLOGICALDRIVEMEMBER         13
#define CPQIDEDISKISSPARE                    14
#define CPQIDEDISKOSNAME                     15
#define CPQIDEDISKTYPE                       16
#define CPQIDEDISKSATAVERSION                17

#define Status_item        8       /* need for trap */

typedef struct  cpqIdeDiskTable_entry{
    netsnmp_index 	    oid_index;
    oid                     Controller;
    oid                     Index;
    char                    Model[41];
    char                    FwRev[9];
    char                    SerialNumber[41];
    int                     Status;
    int                     Condition;
    int                     Capacity;
    int                     SmartEnabled;
    int                     TransferMode;
    int                     Channel;
    int                     Number;
    int                     LogicalDriveMember;
    int                     IsSpare;
    char                    OsName[256];
    int                     Type;
    int                     SataVersion;
    int                     OldStatus;
} netsnmp_idedisk_entry;

#endif                          /* CPQIDEDISK_H */
