/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.container.conf 17798 2009-10-27 06:44:54Z magfr $
 */
#ifndef CPQIDEATADISKTABLE_H
#define CPQIDEATADISKTABLE_H

extern int SataDiskCondition;

typedef struct cpqIdeAtaDiskTable_entry_s {
    netsnmp_index   oid_index;

    /*
     * Index values 
     */
    oid            cpqIdeAtaDiskControllerIndex;
    oid            cpqIdeAtaDiskIndex;

    /*
     * Column values 
     */
    char            cpqIdeAtaDiskModel[41];
    size_t          cpqIdeAtaDiskModel_len;
    char            cpqIdeAtaDiskFwRev[9];
    size_t          cpqIdeAtaDiskFwRev_len;
    char            cpqIdeAtaDiskSerialNumber[41];
    size_t          cpqIdeAtaDiskSerialNumber_len;
    long            cpqIdeAtaDiskStatus;
    long            cpqIdeAtaDiskCondition;
    unsigned long   cpqIdeAtaDiskCapacity;
    long            cpqIdeAtaDiskSmartEnabled;
    long            cpqIdeAtaDiskTransferMode;
    long            cpqIdeAtaDiskChannel;
    long            cpqIdeAtaDiskNumber;
    long            cpqIdeAtaDiskLogicalDriveMember;
    long            cpqIdeAtaDiskIsSpare;
    char            cpqIdeAtaDiskOsName[256];
    size_t          cpqIdeAtaDiskOsName_len;
    long            cpqIdeAtaDiskType;
    long            cpqIdeAtaDiskSataVersion;
    long            cpqIdeAtaDiskMediaType;
    long            cpqIdeAtaDiskSSDWearStatus;
    long            cpqIdeAtaDiskPowerOnHours;
    long            cpqIdeAtaDiskSSDPercntEndrnceUsed;
    long            cpqIdeAtaDiskSSDEstTimeRemainingHours;
    long            cpqIdeAtaDiskCurrTemperature;
    long            cpqIdeAtaDiskTemperatureThreshold;


    int             OldStatus;
    int             OldSSDWearStatus;
    int             valid;
} cpqIdeAtaDiskTable_entry;

/*
 * function declarations 
 */
cpqIdeAtaDiskTable_entry *
    cpqIdeAtaDiskTable_createEntry(netsnmp_container *, oid, oid );
void            init_cpqIdeAtaDiskTable(void);
void            initialize_table_cpqIdeAtaDiskTable(void);
Netsnmp_Node_Handler cpqIdeAtaDiskTable_handler;

/*
 * column number definitions for table cpqIdeAtaDiskTable 
 */
#define COLUMN_CPQIDEATADISKCONTROLLERINDEX		1
#define COLUMN_CPQIDEATADISKINDEX		2
#define COLUMN_CPQIDEATADISKMODEL		3
#define COLUMN_CPQIDEATADISKFWREV		4
#define COLUMN_CPQIDEATADISKSERIALNUMBER		5
#define COLUMN_CPQIDEATADISKSTATUS		6
#define COLUMN_CPQIDEATADISKCONDITION		7
#define COLUMN_CPQIDEATADISKCAPACITY		8
#define COLUMN_CPQIDEATADISKSMARTENABLED		9
#define COLUMN_CPQIDEATADISKTRANSFERMODE		10
#define COLUMN_CPQIDEATADISKCHANNEL		11
#define COLUMN_CPQIDEATADISKNUMBER		12
#define COLUMN_CPQIDEATADISKLOGICALDRIVEMEMBER		13
#define COLUMN_CPQIDEATADISKISSPARE		14
#define COLUMN_CPQIDEATADISKOSNAME		15
#define COLUMN_CPQIDEATADISKTYPE		16
#define COLUMN_CPQIDEATADISKSATAVERSION		17
#define COLUMN_CPQIDEATADISKMEDIATYPE               18
#define COLUMN_CPQIDEATADISKSSDWEARSTATUS           19
#define COLUMN_CPQIDEATADISKPOWERONHOURS            20
#define COLUMN_CPQIDEATADISKSSDPERCNTENDRNCEUSED    21
#define COLUMN_CPQIDEATADISKSSDESTTIMEREMAININGHOURS 22
#define COLUMN_CPQIDEATADISKCURRTEMPERATURE         23
#define COLUMN_CPQIDEATADISKTEMPERATURETHRESHOLD    24

#endif                          /* CPQIDEATADISKTABLE_H */
