/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef CPQSASPHYDRV_H
#define CPQSASPHYDRV_H

/*
 * function declarations 
 */
void initialize_table_cpqSasPhyDrvTable();
int cpqSasPhyDrvTable_handler();

/*
 * cpqSasPhyDrv_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

extern int DiskCondition;
extern oid cpqSasPhyDrvTable_oid[];
extern size_t   cpqSasPhyDrvTable_oid_len;

#define CPQSASPHYDRVHBAINDEX                    1
#define CPQSASPHYDRVINDEX                       2
#define CPQSASPHYDRVLOCATIONSTRING              3
#define CPQSASPHYDRVMODEL                       4
#define CPQSASPHYDRVSTATUS                      5
#define CPQSASPHYDRVCONDITION                   6
#define CPQSASPHYDRVFWREV                       7
#define CPQSASPHYDRVSIZE                        8
#define CPQSASPHYDRVUSEDREALLOCS                9
#define CPQSASPHYDRVSERIALNUM                  10
#define CPQSASPHYDRVMEMBERLOGDRV               11
#define CPQSASPHYDRVROTATIONALSPEED            12
#define CPQSASPHYDRVOSNAME                     13
#define CPQSASPHYDRVPLACEMENT                  14
#define CPQSASPHYDRVHOTPLUG                    15
#define CPQSASPHYDRVTYPE                       16
#define CPQSASPHYDRVSASADDRESS                 17

#define Status_item        8       /* need for trap */

typedef struct  cpqSasPhyDrvTable_entry{
    netsnmp_index 	    oid_index;
    oid                     Hba;
    oid                     Index;
    char                    LocationString[256];
    char                    Model[41];
    int                     Status;
    int                     Condition;
    char                    FWRev[9];
    int                     Size;
    unsigned long           UsedReallocs;
    char                    SerialNum[41];
    int                     MemberLogDrv;
    int                     RotationalSpeed;
    char                    OsName[256];
    int                     Placement;
    int                     HotPlug;
    int                     Type;
    char                    SasAddress[17];
    unsigned long           Capacity;
    int                     StatusTrapCount;
    int                     OldStatus;
    int                     PredictiveFailure;
    int                     PhyIdentifier;
    int                     DrvType;
    char                    HWLocation[128];
} netsnmp_sasphydrv_entry;

#endif                          /* CPQSASPHYDRV_H */
