/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.container.conf 17798 2009-10-27 06:44:54Z magfr $
 */
#ifndef CPQSASHBATABLE_H
#define CPQSASHBATABLE_H

extern int       HbaCondition;
extern oid       cpqSasHbaTable_oid[];
extern size_t    cpqSasHbaTable_oid_len;

typedef struct cpqSasHbaTable_entry_s {
    netsnmp_index   oid_index;

    /*
     * Index values 
     */
    oid            cpqSasHbaIndex;

    /*
     * Column values 
     */
    char            cpqSasHbaHwLocation[128];
    size_t          cpqSasHbaHwLocation_len;
    long            cpqSasHbaModel;
    long            cpqSasHbaStatus;
    long            cpqSasHbaCondition;
    long            cpqSasHbaOverallCondition;
    char            cpqSasHbaSerialNumber[81];
    size_t          cpqSasHbaSerialNumber_len;
    char            cpqSasHbaFwVersion[17];
    size_t          cpqSasHbaFwVersion_len;
    char            cpqSasHbaBiosVersion[17];
    size_t          cpqSasHbaBiosVersion_len;

    char            host[20];
    long            OldStatus;
    oid             cpqHoFwVerIndex;

    sas_connector_info Reference[32];
    int             valid;
} cpqSasHbaTable_entry;
/*
 * function declarations 
 */
cpqSasHbaTable_entry *
        cpqSasHbaTable_createEntry(netsnmp_container * container,
                                   oid cpqSasHbaIndex);

void            init_cpqSasHbaTable(void);
void            initialize_table_cpqSasHbaTable(void);
Netsnmp_Node_Handler cpqSasHbaTable_handler;

/*
 * column number definitions for table cpqSasHbaTable 
 */
#define COLUMN_CPQSASHBAINDEX		1
#define COLUMN_CPQSASHBAHWLOCATION		2
#define COLUMN_CPQSASHBAMODEL		3
#define COLUMN_CPQSASHBASTATUS		4
#define COLUMN_CPQSASHBACONDITION		5
#define COLUMN_CPQSASHBAOVERALLCONDITION		6
#define COLUMN_CPQSASHBASERIALNUMBER		7
#define COLUMN_CPQSASHBAFWVERSION		8
#define COLUMN_CPQSASHBABIOSVERSION		9
#endif                          /* CPQSASHBATABLE_H */
