/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "cpqScsi.h"
#include "common/scsi_info.h"
#include "cpqSasHbaTable.h"
#include "cpqSasPhyDrvTable.h"
#include "hpHelper.h"

#define CPQMIB                  5
#define CPQMIBREVMAJOR		1
#define CPQMIBREVMINOR		38

/*
 * cpqScsiMib_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid             cpqScsiMib_oid[] = { 1, 3, 6, 1, 4, 1, 232, 5, 1 };
size_t          cpqScsiMib_oid_len = OID_LENGTH(cpqScsiMib_oid);


#define CPQSCSIMIBREVMAJOR		1
#define CPQSCSIMIBREVMINOR		2
#define CPQSCSIMIBCONDITION		3

/** Initializes the cpqScsi module */
void
init_cpqScsi(void)
{

    DEBUGMSGTL(("cpqScsi", "Initializing\n"));

    cpqHostMibStatusArray[CPQMIB].major = CPQMIBREVMAJOR;
    cpqHostMibStatusArray[CPQMIB].minor = CPQMIBREVMINOR;
    cpqHoMibHealthStatusArray[CPQMIBHEALTHINDEX] = MIB_CONDITION_OK;

    /*
     * register ourselves with the agent to handle our mib tree 
     */
    netsnmp_register_scalar_group(
        netsnmp_create_handler_registration("cpqScsi", cpqScsi_handler,
                             cpqScsiMib_oid, cpqScsiMib_oid_len,
                             HANDLER_CAN_RONLY),
        CPQSCSIMIBREVMAJOR, CPQSCSIMIBCONDITION);

    initialize_table_cpqSasHbaTable();
    initialize_table_cpqSasPhyDrvTable();

    /*
     * place any other initialization junk you need here 
     */
    cpqHostMibStatusArray[CPQMIB].stat = MIB_STATUS_AVAILABLE;
    cpqHostMibStatusArray[CPQMIB].cond = MIB_CONDITION_OK;

}

int
cpqScsi_handler(netsnmp_mib_handler          *handler,
               netsnmp_handler_registration *reginfo,
               netsnmp_agent_request_info   *reqinfo,
               netsnmp_request_info         *requests)
{
    long val = 0;

    switch (reqinfo->mode) {
    case MODE_GET:
        switch (requests->requestvb->name[ reginfo->rootoid_len - 2 ]) {
            case CPQSCSIMIBREVMAJOR:
                val = CPQMIBREVMAJOR;
                break;
            case CPQSCSIMIBREVMINOR:
                val = CPQMIBREVMINOR;
                break;
            case CPQSCSIMIBCONDITION:
                val = cpqHoMibHealthStatusArray[CPQMIBHEALTHINDEX];
                break;
            default:
                /*
                * An unsupported/unreadable column (if applicable)
                */
                snmp_log(LOG_ERR, "unknown object (%lu) in cpqScsi_handler\n",
                     requests->requestvb->name[ reginfo->rootoid_len - 2 ]);
                netsnmp_set_request_error( reqinfo, requests, 
                                            SNMP_NOSUCHOBJECT );
                return SNMP_ERR_NOERROR;
        }
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)&val, sizeof(val));
        break;

    default:
        snmp_log(LOG_ERR, "unknown mode (%d) in cpqScsi_handlery\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;

}


