/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef CPQSASHBA_H
#define CPQSASHBA_H

/*
 * function declarations 
 */
void initialize_table_cpqSasHbaTable();
int cpqSasHbaTable_handler();
extern int HbaCondition;


/*
 * cpqSasHbaTable_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

extern oid cpqSasHbaTable_oid[];
extern size_t   cpqSasHbaTable_oid_len;

#define CPQSASHBAINDEX                1
#define CPQSASHBAHWLOCATION           2
#define CPQSASHBAMODEL                3
#define CPQSASHBASTATUS               4
#define CPQSASHBACONDITION            5
#define CPQSASHBAOVERALLCONDITION     6
#define CPQSASHBASERIALNUM            7
#define CPQSASHBAFWVERSION            8
#define CPQSASHBABIOSVERSION          9

typedef struct  cpqSasHbaTable_entry{
    netsnmp_index  oid_index;
    int            Hba;  
    char           HwLocation[128];
    int            Model;    
    int            Status; 
    int            Condition;
    int            OverallCondition;
    char           SerialNum[81];
    char           FWVersion[17];
    char           BiosVersion[17];
    char           Host[20];
} netsnmp_sashba_entry;

#endif                          /* CPQSASHBA_H */
